In [1]:
import soccerdata as sd
import datetime
import pandas as pd

[07/07/25 12:58:13] INFO     No custom team name replacements found. You can configure these in       ]8;id=394128;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_config.py\_config.py]8;;\:]8;id=845393;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_config.py#87\87]8;;\
                             lib/soccerdata/config/teamname_replacements.json.

                    INFO     Custom league dict loaded from lib/soccerdata/config/league_dict.json.  ]8;id=222430;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_config.py\_config.py]8;;\:]8;id=681046;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_config.py#180\180]8;;\

In [2]:
def get_all_seasons_string(first_season, last_season, step=1, skip_seasons=None):
    """
    Returns a string representation of all seasons from first_season to last_season.
    first_season 9798, last_season 1819, skip_season 1516
    8596, 9697, 9798, 9899, 9900, 0001, 0102, 0203, 0304, 0405, 0506, 0607, 0708, 0809, 0910, 1011, 1112, 1213, 1314, 1415, 1516, 1617, 1718, 1819
    """
    seasons = []
    season_year1, season_year2 = str(first_season)[:2], str(first_season)[2:]
    last_season_year1, _ = str(last_season)[:2], str(last_season)[2:]
    while (season_year1 != last_season_year1):
        if skip_seasons and f"{season_year1}{season_year2}" in skip_seasons:
            pass
        else:
            seasons.append(f"{season_year1}{season_year2}")
        season_year2 = str((int(season_year2) + step)%100).zfill(2)
        season_year1 = str((int(season_year1) + step)%100).zfill(2)
    if skip_seasons and f"{season_year1}{season_year2}" in skip_seasons:
        pass
    else:
        seasons.append(f"{season_year1}{season_year2}")
    return seasons

In [3]:
use_cache = False
get_current_season_only = True

In [4]:
fbref = sd.FBref(leagues=["FIFA Club World Cup"], seasons=['2526'], no_cache=False)
df = fbref.read_schedule(force_cache=False)
df.sort_values(by=['date'], ascending=False)

                    INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=85763;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py\_common.py]8;;\:]8;id=277769;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py#92\92]8;;\

/Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/fbref.py:157: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

url_fixtures: https://fbref.com/en/comps/719/schedule/FIFA-Club-World-Cup-Scores-and-Fixtures/lib/soccerdata/data/FBref/schedule_FIFA Club World Cup_2526.html
td: b'<td class="right " data-stat="start_time" csk="19:30:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1748745000" data-venue-time="19:30">19:30</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750014000" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750003200" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750024800" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="20:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1749945600" data-venue-time="20:00">20:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750100400" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750111200" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="19:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750039200" data-venue-time="19:00">19:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750186800" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750176000" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="19:05:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750201500" data-venue-time="19:05">19:05</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750122000" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750262400" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750273200" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750208400" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750284000" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750348800" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750359600" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750370400" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750294800" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750435200" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="14:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750442400" data-venue-time="14:00">14:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="17:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750456800" data-venue-time="17:00">17:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750381200" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750532400" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750521600" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750543200" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750467600" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750608000" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750618800" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750554000" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750629600" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750705200" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750705200" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750640400" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="14:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750791600" data-venue-time="14:00">14:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750791600" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750726800" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750726800" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750878000" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750878000" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750813200" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750813200" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750964400" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750964400" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750899600" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="18:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750899600" data-venue-time="18:00">18:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="20:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750986000" data-venue-time="20:00">20:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1750986000" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751126400" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="16:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751140800" data-venue-time="16:00">16:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751212800" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="16:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751227200" data-venue-time="16:00">16:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751310000" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751396400" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751331600" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751418000" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751655600" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="12:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751731200" data-venue-time="12:00">12:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="16:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751745600" data-venue-time="16:00">16:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="21:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1751677200" data-venue-time="21:00">21:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1752001200" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
td: b'<td class="right " data-stat="start_time" csk="15:00:00"><span class="venuetime" data-venue-time-only="1" data-venue-epoch="1752087600" data-venue-time="15:00">15:00</span> <span class="localtime" data-label="your time"></span></td>'
local_span: b'<span class="localtime" data-label="your time"></span>'
<lxml.etree._ElementTree object at 0x111476d80>
df.columns: Index(['round', 'week', 'day', 'date', 'time', 'home_team', 'score',
       'away_team', 'attendance', 'venue', 'referee', 'match_report', 'notes',
       'local_time', 'league', 'season'],
      dtype='object')

                                                                               round  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid              Semi-finals
                           2025-07-08 Chelsea-Fluminense                 Semi-finals
                           2025-07-05 Real Madrid-Dortmund            Quarter-finals
                           2025-07-05 Paris S-G-Bayern Munich         Quarter-finals
                           2025-07-04 Palmeiras-Chelsea               Quarter-finals
...                                                                              ...
                           2025-06-15 Paris S-G-Atlético Madrid          Group stage
                           2025-06-15 Palmeiras-Porto                    Group stage
                           2025-06-15 Botafogo (RJ)-Seattle Sounders     Group stage
                           2025-06-14 Al Ahly-Inter Miami                Group stage
                           2025-05-31 LAFC-América                     Play-in match

                                                                      week  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid           <NA>
                           2025-07-08 Chelsea-Fluminense              <NA>
                           2025-07-05 Real Madrid-Dortmund            <NA>
                           2025-07-05 Paris S-G-Bayern Munich         <NA>
                           2025-07-04 Palmeiras-Chelsea               <NA>
...                                                                    ...
                           2025-06-15 Paris S-G-Atlético Madrid          1
                           2025-06-15 Palmeiras-Porto                    1
                           2025-06-15 Botafogo (RJ)-Seattle Sounders     1
                           2025-06-14 Al Ahly-Inter Miami                1
                           2025-05-31 LAFC-América                    <NA>

                                                                      day  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid           Wed
                           2025-07-08 Chelsea-Fluminense              Tue
                           2025-07-05 Real Madrid-Dortmund            Sat
                           2025-07-05 Paris S-G-Bayern Munich         Sat
                           2025-07-04 Palmeiras-Chelsea               Fri
...                                                                   ...
                           2025-06-15 Paris S-G-Atlético Madrid       Sun
                           2025-06-15 Palmeiras-Porto                 Sun
                           2025-06-15 Botafogo (RJ)-Seattle Sounders  Sun
                           2025-06-14 Al Ahly-Inter Miami             Sat
                           2025-05-31 LAFC-América                    Sat

                                                                           date  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid          2025-07-09
                           2025-07-08 Chelsea-Fluminense             2025-07-08
                           2025-07-05 Real Madrid-Dortmund           2025-07-05
                           2025-07-05 Paris S-G-Bayern Munich        2025-07-05
                           2025-07-04 Palmeiras-Chelsea              2025-07-04
...                                                                         ...
                           2025-06-15 Paris S-G-Atlético Madrid      2025-06-15
                           2025-06-15 Palmeiras-Porto                2025-06-15
                           2025-06-15 Botafogo (RJ)-Seattle Sounders 2025-06-15
                           2025-06-14 Al Ahly-Inter Miami            2025-06-14
                           2025-05-31 LAFC-América                   2025-05-31

                                                                       time  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid           15:00
                           2025-07-08 Chelsea-Fluminense              15:00
                           2025-07-05 Real Madrid-Dortmund            16:00
                           2025-07-05 Paris S-G-Bayern Munich         12:00
                           2025-07-04 Palmeiras-Chelsea               21:00
...                                                                     ...
                           2025-06-15 Paris S-G-Atlético Madrid       12:00
                           2025-06-15 Palmeiras-Porto                 18:00
                           2025-06-15 Botafogo (RJ)-Seattle Sounders  19:00
                           2025-06-14 Al Ahly-Inter Miami             20:00
                           2025-05-31 LAFC-América                    19:30

                                                                          home_team  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid               Paris S-G
                           2025-07-08 Chelsea-Fluminense                    Chelsea
                           2025-07-05 Real Madrid-Dortmund              Real Madrid
                           2025-07-05 Paris S-G-Bayern Munich             Paris S-G
                           2025-07-04 Palmeiras-Chelsea                   Palmeiras
...                                                                             ...
                           2025-06-15 Paris S-G-Atlético Madrid           Paris S-G
                           2025-06-15 Palmeiras-Porto                     Palmeiras
                           2025-06-15 Botafogo (RJ)-Seattle Sounders  Botafogo (RJ)
                           2025-06-14 Al Ahly-Inter Miami                   Al Ahly
                           2025-05-31 LAFC-América                             LAFC

                                                                     score  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid           <NA>
                           2025-07-08 Chelsea-Fluminense              <NA>
                           2025-07-05 Real Madrid-Dortmund             3–2
                           2025-07-05 Paris S-G-Bayern Munich          2–0
                           2025-07-04 Palmeiras-Chelsea                1–2
...                                                                    ...
                           2025-06-15 Paris S-G-Atlético Madrid        4–0
                           2025-06-15 Palmeiras-Porto                  0–0
                           2025-06-15 Botafogo (RJ)-Seattle Sounders   2–1
                           2025-06-14 Al Ahly-Inter Miami              0–0
                           2025-05-31 LAFC-América                     2–1

                                                                             away_team  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                Real Madrid
                           2025-07-08 Chelsea-Fluminense                    Fluminense
                           2025-07-05 Real Madrid-Dortmund                    Dortmund
                           2025-07-05 Paris S-G-Bayern Munich            Bayern Munich
                           2025-07-04 Palmeiras-Chelsea                        Chelsea
...                                                                                ...
                           2025-06-15 Paris S-G-Atlético Madrid        Atlético Madrid
                           2025-06-15 Palmeiras-Porto                            Porto
                           2025-06-15 Botafogo (RJ)-Seattle Sounders  Seattle Sounders
                           2025-06-14 Al Ahly-Inter Miami                  Inter Miami
                           2025-05-31 LAFC-América                             América

                                                                      attendance  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                 <NA>
                           2025-07-08 Chelsea-Fluminense                    <NA>
                           2025-07-05 Real Madrid-Dortmund                 76611
                           2025-07-05 Paris S-G-Bayern Munich              66937
                           2025-07-04 Palmeiras-Chelsea                    65782
...                                                                          ...
                           2025-06-15 Paris S-G-Atlético Madrid            80619
                           2025-06-15 Palmeiras-Porto                      46275
                           2025-06-15 Botafogo (RJ)-Seattle Sounders       30151
                           2025-06-14 Al Ahly-Inter Miami                  60927
                           2025-05-31 LAFC-América                         20714

                                                                                                       venue  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                   MetLife Stadium (Neutral Site)
                           2025-07-08 Chelsea-Fluminense                      MetLife Stadium (Neutral Site)
                           2025-07-05 Real Madrid-Dortmund                    MetLife Stadium (Neutral Site)
                           2025-07-05 Paris S-G-Bayern Munich           Mercedes-Benz Stadium (Neutral Site)
                           2025-07-04 Palmeiras-Chelsea               Lincoln Financial Field (Neutral Site)
...                                                                                                      ...
                           2025-06-15 Paris S-G-Atlético Madrid                     Rose Bowl (Neutral Site)
                           2025-06-15 Palmeiras-Porto                         MetLife Stadium (Neutral Site)
                           2025-06-15 Botafogo (RJ)-Seattle Sounders              Lumen Field (Neutral Site)
                           2025-06-14 Al Ahly-Inter Miami                   Hard Rock Stadium (Neutral Site)
                           2025-05-31 LAFC-América                                BMO Stadium (Neutral Site)

                                                                              referee  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                      <NA>
                           2025-07-08 Chelsea-Fluminense                         <NA>
                           2025-07-05 Real Madrid-Dortmund               Ramon Abatti
                           2025-07-05 Paris S-G-Bayern Munich          Anthony Taylor
                           2025-07-04 Palmeiras-Chelsea               Alireza Faghani
...                                                                               ...
                           2025-06-15 Paris S-G-Atlético Madrid         István Kovács
                           2025-06-15 Palmeiras-Porto                   Said Martínez
                           2025-06-15 Botafogo (RJ)-Seattle Sounders     Glenn Nyberg
                           2025-06-14 Al Ahly-Inter Miami             Alireza Faghani
                           2025-05-31 LAFC-América                     Wilton Sampaio

                                                                                                           match_report  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                                                        None
                           2025-07-08 Chelsea-Fluminense                                                           None
                           2025-07-05 Real Madrid-Dortmund            /en/matches/013d214a/Real-Madrid-Dortmund-July...
                           2025-07-05 Paris S-G-Bayern Munich         /en/matches/3c59bc84/Paris-Saint-Germain-Bayer...
                           2025-07-04 Palmeiras-Chelsea               /en/matches/54878ae5/Palmeiras-Chelsea-July-4-...
...                                                                                                                 ...
                           2025-06-15 Paris S-G-Atlético Madrid       /en/matches/416db7a8/Paris-Saint-Germain-Atlet...
                           2025-06-15 Palmeiras-Porto                 /en/matches/debde3b8/Palmeiras-Porto-June-15-2...
                           2025-06-15 Botafogo (RJ)-Seattle Sounders  /en/matches/43308ee3/Botafogo-RJ-Seattle-Sound...
                           2025-06-14 Al Ahly-Inter Miami             /en/matches/c446a386/Al-Ahly-Inter-Miami-June-...
                           2025-05-31 LAFC-América                    /en/matches/cb1662fa/Los-Angeles-FC-America-Ma...

                                                                                    notes  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                          <NA>
                           2025-07-08 Chelsea-Fluminense                             <NA>
                           2025-07-05 Real Madrid-Dortmund                           <NA>
                           2025-07-05 Paris S-G-Bayern Munich                        <NA>
                           2025-07-04 Palmeiras-Chelsea                              <NA>
...                                                                                   ...
                           2025-06-15 Paris S-G-Atlético Madrid                      <NA>
                           2025-06-15 Palmeiras-Porto                                <NA>
                           2025-06-15 Botafogo (RJ)-Seattle Sounders                 <NA>
                           2025-06-14 Al Ahly-Inter Miami                            <NA>
                           2025-05-31 LAFC-América                    Required Extra Time

                                                                     local_time  \
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid            15:00:00
                           2025-07-08 Chelsea-Fluminense               15:00:00
                           2025-07-05 Real Madrid-Dortmund             16:00:00
                           2025-07-05 Paris S-G-Bayern Munich          12:00:00
                           2025-07-04 Palmeiras-Chelsea                21:00:00
...                                                                         ...
                           2025-06-15 Paris S-G-Atlético Madrid        12:00:00
                           2025-06-15 Palmeiras-Porto                  18:00:00
                           2025-06-15 Botafogo (RJ)-Seattle Sounders   19:00:00
                           2025-06-14 Al Ahly-Inter Miami              20:00:00
                           2025-05-31 LAFC-América                     19:30:00

                                                                       game_id
league              season game
FIFA Club World Cup 2526   2025-07-09 Paris S-G-Real Madrid                NaN
                           2025-07-08 Chelsea-Fluminense                   NaN
                           2025-07-05 Real Madrid-Dortmund            013d214a
                           2025-07-05 Paris S-G-Bayern Munich         3c59bc84
                           2025-07-04 Palmeiras-Chelsea               54878ae5
...                                                                        ...
                           2025-06-15 Paris S-G-Atlético Madrid       416db7a8
                           2025-06-15 Palmeiras-Porto                 debde3b8
                           2025-06-15 Botafogo (RJ)-Seattle Sounders  43308ee3
                           2025-06-14 Al Ahly-Inter Miami             c446a386
                           2025-05-31 LAFC-América                    cb1662fa

[63 rows x 15 columns]

In [20]:
fbref = sd.FBref()
leagues = ["UEFA Champions League", "INT-World Cup", "INT-European Championships", "Big 5 European Leagues Combined"]
leagues = ["UEFA Champions League"]
first_seasons = ["9091", "3031", "0001", "3031"]
skip_seasons = [['3940', '4041', '4142', '4243', '4344', '4546'], ['4243', '4344', '4647'], None, ['3940', '4041', '4142', '4243', '4344', '4546']]  # Seasons to skip due to WWII
steps = [1, 4, 4, 1]  # Steps for each league to get the first season
leagues_df = fbref.read_leagues()

dfs_fbref = []
for i, league in enumerate(leagues):
    print(f"Processing league: {league}")
    first_season = first_seasons[i]
    last_season = leagues_df.loc[league, 'last_season']
    seasons = get_all_seasons_string(first_season, last_season, step=steps[i], skip_seasons=skip_seasons[i])
    if get_current_season_only:
        seasons = [seasons[-1]]
    print(f"Seasons for {league}: {seasons}")
    fbref = sd.FBref(leagues=[league], seasons=seasons)
    df = fbref.read_schedule(force_cache=use_cache) if seasons else None
    df = df.reset_index() if df is not None else None
    dfs_fbref.append(df) if df is not None else None
fbref_df = pd.concat(dfs_fbref, ignore_index=True) if dfs_fbref else pd.DataFrame()

[07/05/25 15:00:40] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=360996;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py\_common.py]8;;\:]8;id=909859;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py#92\92]8;;\

                    INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=370149;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py\_common.py]8;;\:]8;id=10362;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py#291\291]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>
Processing league: UEFA Champions League
Seasons for UEFA Champions League: ['2425']

/Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

                    INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=25967;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py\_common.py]8;;\:]8;id=523162;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/_common.py#92\92]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>

/Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/optibet_lib/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

In [21]:
fbref_df.sort_values(by=['date'], ascending=False)

,league,season,game,round,week,day,date,time,home_team,home_xg,score,away_xg,away_team,attendance,venue,referee,match_report,notes,game_id
188,UEFA Champions League,2425,2025-05-31 Paris S-G-Inter,Final,<NA>,Sat,2025-05-31,21:00,Paris S-G,<NA>,<NA>,<NA>,Inter,<NA>,Allianz Arena,<NA>,None,<NA>,NaN
187,UEFA Champions League,2425,2025-05-07 Paris S-G-Arsenal,Semi-finals,<NA>,Wed,2025-05-07,21:00,Paris S-G,1.7,2–1,2.8,Arsenal,47511,Parc des Princes,Felix Zwayer,/en/matches/a73bdd5b/Paris-Saint-Germain-Arsen...,Leg 2 of 2; Paris S-G won,a73bdd5b
186,UEFA Champions League,2425,2025-05-06 Inter-Barcelona,Semi-finals,<NA>,Tue,2025-05-06,21:00,Inter,2.2,4–3,2.8,Barcelona,75504,Stadio Giuseppe Meazza,Szymon Marciniak,/en/matches/ff6aaaa9/Internazionale-Barcelona-...,Leg 2 of 2; Inter won; Required Extra Time,ff6aaaa9
185,UEFA Champions League,2425,2025-04-30 Barcelona-Inter,Semi-finals,<NA>,Wed,2025-04-30,21:00,Barcelona,1.4,3–3,0.8,Inter,50314,Estadi Olímpic Lluís Companys,Clément Turpin,/en/matches/4b3ea62f/Barcelona-Internazionale-...,Leg 1 of 2,4b3ea62f
184,UEFA Champions League,2425,2025-04-29 Arsenal-Paris S-G,Semi-finals,<NA>,Tue,2025-04-29,20:00,Arsenal,1.7,0–1,1.2,Paris S-G,59664,Emirates Stadium,Slavko Vinčič,/en/matches/d85808e6/Arsenal-Paris-Saint-Germa...,Leg 1 of 2,d85808e6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2,UEFA Champions League,2425,2024-09-17 Milan-Liverpool,League phase,1,Tue,2024-09-17,21:00,Milan,0.6,1–3,3.1,Liverpool,59826,Stadio Giuseppe Meazza,Espen Eskås,/en/matches/54ed5557/Milan-Liverpool-September...,<NA>,54ed5557
1,UEFA Champions League,2425,2024-09-17 Juventus-PSV Eindhoven,League phase,1,Tue,2024-09-17,18:45,Juventus,2.9,3–1,1.0,PSV Eindhoven,40417,Allianz Stadium,Alejandro Hernández,/en/matches/931cd5fb/Juventus-PSV-Eindhoven-Se...,<NA>,931cd5fb
4,UEFA Champions League,2425,2024-09-17 Sporting CP-Lille,League phase,1,Tue,2024-09-17,20:00,Sporting CP,1.6,2–0,0.4,Lille,40024,Estádio José Alvalade,Donatas Rumšas,/en/matches/aaca158d/Sporting-CP-Lille-Septemb...,<NA>,aaca158d
5,UEFA Champions League,2425,2024-09-17 Young Boys-Aston Villa,League phase,1,Tue,2024-09-17,18:45,Young Boys,0.6,0–3,2.0,Aston Villa,31500,Stadion Wankdorf,Georgi Kabakov,/en/matches/568274fc/Young-Boys-Aston-Villa-Se...,<NA>,568274fc
0,UEFA Champions League,2425,2024-09-17 Bayern Munich-Dinamo Zagreb,League phase,1,Tue,2024-09-17,21:00,Bayern Munich,5.9,9–2,0.7,Dinamo Zagreb,75000,Allianz Arena,Juan Martínez,/en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagr...,<NA>,7c5c2955

In [8]:
### Big 5 European Leagues Combined ###
current_date = datetime.datetime.now()
current_year = current_date.year
get_current_season_only = False  # Set to True to only get the current season
use_cache = True  # Set to False to force a fresh download of the data


leagues = ["Big 5 European Leagues Combined"]
# Determine the correct season depending on the current date
if current_date.month < 8:  # Before August
    current_season_big5 = f"{str(current_year-1)[2:]}-{str(current_year)[2:]}"
else:  # August or later
    current_season_big5 = f"{str(current_year)[2:]}-{str(current_year+1)[2:]}"
if get_current_season_only:
    seasons = [current_season_big5]
else:
    seasons = [f"{str(year)[2:]}-{str(year+1)[2:]}" for year in range(1930, current_year+1)]
    [seasons.remove(f"{str(year)[2:]}-{str(year+1)[2:]}") for year in range(1939, 1946)]
fbref = sd.FBref(leagues=leagues, seasons=seasons)
big5 = fbref.read_schedule(force_cache=use_cache) if seasons else None
big5 = big5.reset_index() if big5 is not None else None

[05/31/25 15:45:16] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=539361;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=906023;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>

/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

[05/31/25 16:08:07] ERROR    Error while scraping                                                    ]8;id=52313;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=472617;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats.
                             Retrying... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url: https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats

[05/31/25 16:08:10] ERROR    Error while scraping                                                    ]8;id=437185;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=564668;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats.
                             Retrying... (attempt 2 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url: https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats

[05/31/25 16:08:13] ERROR    Error while scraping                                                    ]8;id=80228;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=800090;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats.
                             Retrying... (attempt 3 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url: https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats

[05/31/25 16:08:16] ERROR    Error while scraping                                                    ]8;id=512254;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=321184;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats.
                             Retrying... (attempt 4 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url: https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats

[05/31/25 16:08:19] ERROR    Error while scraping                                                    ]8;id=410698;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=969325;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats.
                             Retrying... (attempt 5 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url: https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats

ConnectionError: Could not download https://fbref.com/en/comps/11/2010-2011/2010-2011-Serie-A-Stats.

In [ ]:
fbref = sd.FBref(leagues=leagues, seasons=seasons)
fbref.read_leagues()

NameError: name 'leagues' is not defined

In [ ]:
leagues_df[leagues_df.index == 'UEFA Champions League']['first_season']

league
UEFA Champions League    9091
Name: first_season, dtype: object

In [15]:
leagues_df.loc['UEFA Champions League', 'first_season']

'9091'

In [28]:
fbref = sd.FBref()
leagues = ["UEFA Champions League"]
leagues_df = fbref.read_leagues()

for league in leagues:
    first_season = leagues_df.loc[league, 'first_season']
    last_season = leagues_df.loc[league, 'last_season']
    print(f"{league} first season: {first_season}, last season: {last_season}")

def get_all_seasons_string(first_season, last_season, step=1, skip_seasons=None):
    """
    Returns a string representation of all seasons from first_season to last_season.
    first_season 9798, last_season 1819, skip_season 1516
    8596, 9697, 9798, 9899, 9900, 0001, 0102, 0203, 0304, 0405, 0506, 0607, 0708, 0809, 0910, 1011, 1112, 1213, 1314, 1415, 1516, 1617, 1718, 1819
    """
    seasons = []
    season_year1, season_year2 = str(first_season)[:2], str(first_season)[2:]
    last_season_year1, _ = str(last_season)[:2], str(last_season)[2:]
    while (season_year1 != last_season_year1):
        if skip_seasons and f"{season_year1}{season_year2}" in skip_seasons:
            pass
        else:
            seasons.append(f"{season_year1}{season_year2}")
        print(f"season_year1: {season_year1}, season_year2: {season_year2}, seasons: {seasons}")
        season_year2 = str((int(season_year2) + step)%100).zfill(2)
        season_year1 = str((int(season_year1) + step)%100).zfill(2)
    if skip_seasons and f"{season_year1}{season_year2}" in skip_seasons:
        pass
    else:
        seasons.append(f"{season_year1}{season_year2}")
    return seasons

leagues = ["UEFA Champions League", "INT-World Cup", "INT-European Championships", "Big 5 European Leagues Combined"]
first_seasons = ["9091", "3031", "0001", "3031"]
skip_seasons = [['3940', '4041', '4142', '4243', '4344', '4546'], ['4243', '4344', '4647'], None, ['3940', '4041', '4142', '4243', '4344', '4546']]  # Seasons to skip due to WWII
steps = [1, 4, 4, 1]  # Steps for each league to get the first season

# Example usage
get_current_season_only = True
dfs_fbref = []
for i, league in enumerate(leagues):
    print(i, league)
    first_season = first_seasons[i]
    last_season = leagues_df.loc[league, 'last_season']
    print(f"{league} first season: {first_season}, last season: {last_season}, skip_seasons: {skip_seasons[i]}, step: {steps[i]}")
    seasons = get_all_seasons_string(first_season, last_season, skip_seasons=skip_seasons[i], step=steps[i])
    if get_current_season_only:
        seasons = [seasons[-1]]
    fbref = sd.FBref(leagues=[league], seasons=seasons)
    # df = fbref.read_schedule(force_cache=use_cache) if seasons else None
    # df = df.reset_index() if df is not None else None
    # dfs_fbref.append(df) if df is not None else None

[05/31/25 17:44:13] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=49638;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=156147;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

                    INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=198506;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=359117;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#291\291]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>
UEFA Champions League first season: 9091, last season: 2425
0 UEFA Champions League
UEFA Champions League first season: 9091, last season: 2425, skip_seasons: ['3940', '4041', '4142', '4243', '4344', '4546'], step: 1
season_year1: 90, season_year2: 91, seasons: ['9091']
season_year1: 91, season_year2: 92, seasons: ['9091', '9192']
season_year1: 92, season_year2: 93, seasons: ['9091', '9192', '9293']
season_year1: 93, season_year2: 94, seasons: ['9091', '9192', '9293', '9394']
season_year1: 94, season_year2: 95, seasons: ['9091', '9192', '9293', '9394', '9495']
season_year1: 95, season_year2: 96, seasons: ['9091', '9192', '9293', '9394', '9495', '9596']
season_year1: 96, season_year2: 97, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697']
season_year1: 97, season_year2: 98, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798']
season_year1: 98, season_year2: 99, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899']
season_year1: 99, season_year2: 00, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900']
season_year1: 00, season_year2: 01, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001']
season_year1: 01, season_year2: 02, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102']
season_year1: 02, season_year2: 03, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203']
season_year1: 03, season_year2: 04, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304']
season_year1: 04, season_year2: 05, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405']
season_year1: 05, season_year2: 06, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506']
season_year1: 06, season_year2: 07, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607']
season_year1: 07, season_year2: 08, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708']
season_year1: 08, season_year2: 09, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809']
season_year1: 09, season_year2: 10, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910']
season_year1: 10, season_year2: 11, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011']
season_year1: 11, season_year2: 12, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112']
season_year1: 12, season_year2: 13, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213']
season_year1: 13, season_year2: 14, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314']
season_year1: 14, season_year2: 15, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415']
season_year1: 15, season_year2: 16, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516']
season_year1: 16, season_year2: 17, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617']
season_year1: 17, season_year2: 18, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718']
season_year1: 18, season_year2: 19, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819']
season_year1: 19, season_year2: 20, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920']
season_year1: 20, season_year2: 21, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021']
season_year1: 21, season_year2: 22, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122']
season_year1: 22, season_year2: 23, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122', '2223']
season_year1: 23, season_year2: 24, seasons: ['9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899', '9900', '0001', '0102', '0203', '0304', '0405', '0506', '0607', '0708', '0809', '0910', '1011', '1112', '1213', '1314', '1415', '1516', '1617', '1718', '1819', '1920', '2021', '2122', '2223', '2324']

/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

                    INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=299896;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=241727;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

1 INT-World Cup
INT-World Cup first season: 3031, last season: 2223, skip_seasons: ['4243', '4344', '4647'], step: 4
season_year1: 30, season_year2: 31, seasons: ['3031']
season_year1: 34, season_year2: 35, seasons: ['3031', '3435']
season_year1: 38, season_year2: 39, seasons: ['3031', '3435', '3839']
season_year1: 42, season_year2: 43, seasons: ['3031', '3435', '3839']
season_year1: 46, season_year2: 47, seasons: ['3031', '3435', '3839']
season_year1: 50, season_year2: 51, seasons: ['3031', '3435', '3839', '5051']
season_year1: 54, season_year2: 55, seasons: ['3031', '3435', '3839', '5051', '5455']
season_year1: 58, season_year2: 59, seasons: ['3031', '3435', '3839', '5051', '5455', '5859']
season_year1: 62, season_year2: 63, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263']
season_year1: 66, season_year2: 67, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667']
season_year1: 70, season_year2: 71, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071']
season_year1: 74, season_year2: 75, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475']
season_year1: 78, season_year2: 79, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879']
season_year1: 82, season_year2: 83, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283']
season_year1: 86, season_year2: 87, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687']
season_year1: 90, season_year2: 91, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091']
season_year1: 94, season_year2: 95, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495']
season_year1: 98, season_year2: 99, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495', '9899']
season_year1: 02, season_year2: 03, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495', '9899', '0203']
season_year1: 06, season_year2: 07, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495', '9899', '0203', '0607']
season_year1: 10, season_year2: 11, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495', '9899', '0203', '0607', '1011']
season_year1: 14, season_year2: 15, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495', '9899', '0203', '0607', '1011', '1415']
season_year1: 18, season_year2: 19, seasons: ['3031', '3435', '3839', '5051', '5455', '5859', '6263', '6667', '7071', '7475', '7879', '8283', '8687', '9091', '9495', '9899', '0203', '0607', '1011', '1415', '1819']

                    INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=174680;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=119375;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

2 INT-European Championships
INT-European Championships first season: 0001, last season: 2425, skip_seasons: None, step: 4
season_year1: 00, season_year2: 01, seasons: ['0001']
season_year1: 04, season_year2: 05, seasons: ['0001', '0405']
season_year1: 08, season_year2: 09, seasons: ['0001', '0405', '0809']
season_year1: 12, season_year2: 13, seasons: ['0001', '0405', '0809', '1213']
season_year1: 16, season_year2: 17, seasons: ['0001', '0405', '0809', '1213', '1617']
season_year1: 20, season_year2: 21, seasons: ['0001', '0405', '0809', '1213', '1617', '2021']

                    INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=411036;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=919328;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

3 Big 5 European Leagues Combined
Big 5 European Leagues Combined first season: 3031, last season: 2425, skip_seasons: ['3940', '4041', '4142', '4243', '4344', '4546'], step: 1
season_year1: 30, season_year2: 31, seasons: ['3031']
season_year1: 31, season_year2: 32, seasons: ['3031', '3132']
season_year1: 32, season_year2: 33, seasons: ['3031', '3132', '3233']
season_year1: 33, season_year2: 34, seasons: ['3031', '3132', '3233', '3334']
season_year1: 34, season_year2: 35, seasons: ['3031', '3132', '3233', '3334', '3435']
season_year1: 35, season_year2: 36, seasons: ['3031', '3132', '3233', '3334', '3435', '3536']
season_year1: 36, season_year2: 37, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637']
season_year1: 37, season_year2: 38, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738']
season_year1: 38, season_year2: 39, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839']
season_year1: 39, season_year2: 40, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839']
season_year1: 40, season_year2: 41, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839']
season_year1: 41, season_year2: 42, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839']
season_year1: 42, season_year2: 43, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839']
season_year1: 43, season_year2: 44, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839']
season_year1: 44, season_year2: 45, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445']
season_year1: 45, season_year2: 46, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445']
season_year1: 46, season_year2: 47, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647']
season_year1: 47, season_year2: 48, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748']
season_year1: 48, season_year2: 49, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849']
season_year1: 49, season_year2: 50, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950']
season_year1: 50, season_year2: 51, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051']
season_year1: 51, season_year2: 52, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152']
season_year1: 52, season_year2: 53, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253']
season_year1: 53, season_year2: 54, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354']
season_year1: 54, season_year2: 55, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455']
season_year1: 55, season_year2: 56, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556']
season_year1: 56, season_year2: 57, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657']
season_year1: 57, season_year2: 58, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758']
season_year1: 58, season_year2: 59, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859']
season_year1: 59, season_year2: 60, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960']
season_year1: 60, season_year2: 61, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061']
season_year1: 61, season_year2: 62, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162']
season_year1: 62, season_year2: 63, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263']
season_year1: 63, season_year2: 64, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364']
season_year1: 64, season_year2: 65, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465']
season_year1: 65, season_year2: 66, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566']
season_year1: 66, season_year2: 67, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667']
season_year1: 67, season_year2: 68, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768']
season_year1: 68, season_year2: 69, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869']
season_year1: 69, season_year2: 70, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970']
season_year1: 70, season_year2: 71, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071']
season_year1: 71, season_year2: 72, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172']
season_year1: 72, season_year2: 73, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273']
season_year1: 73, season_year2: 74, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374']
season_year1: 74, season_year2: 75, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475']
season_year1: 75, season_year2: 76, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576']
season_year1: 76, season_year2: 77, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677']
season_year1: 77, season_year2: 78, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778']
season_year1: 78, season_year2: 79, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879']
season_year1: 79, season_year2: 80, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980']
season_year1: 80, season_year2: 81, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081']
season_year1: 81, season_year2: 82, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182']
season_year1: 82, season_year2: 83, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283']
season_year1: 83, season_year2: 84, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384']
season_year1: 84, season_year2: 85, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485']
season_year1: 85, season_year2: 86, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586']
season_year1: 86, season_year2: 87, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687']
season_year1: 87, season_year2: 88, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788']
season_year1: 88, season_year2: 89, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889']
season_year1: 89, season_year2: 90, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990']
season_year1: 90, season_year2: 91, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091']
season_year1: 91, season_year2: 92, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192']
season_year1: 92, season_year2: 93, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293']
season_year1: 93, season_year2: 94, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293', '9394']
season_year1: 94, season_year2: 95, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293', '9394', '9495']
season_year1: 95, season_year2: 96, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293', '9394', '9495', '9596']
season_year1: 96, season_year2: 97, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293', '9394', '9495', '9596', '9697']
season_year1: 97, season_year2: 98, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798']
season_year1: 98, season_year2: 99, seasons: ['3031', '3132', '3233', '3334', '3435', '3536', '3637', '3738', '3839', '4445', '4647', '4748', '4849', '4950', '5051', '5152', '5253', '5354', '5455', '5556', '5657', '5758', '5859', '5960', '6061', '6162', '6263', '6364', '6465', '6566', '6667', '6768', '6869', '6970', '7071', '7172', '7273', '7374', '7475', '7576', '7677', '7778', '7879', '7980', '8081', '8182', '8283', '8384', '8485', '8586', '8687', '8788', '8889', '8990', '9091', '9192', '9293', '9394', '9495', '9596', '9697', '9798', '9899']

                    INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=953466;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=919345;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

In [ ]:
get_current_season_only = True  # Set to True to only get the current season
current_year = 2025  # Set the current year for the UEFA Champions League
use_cache = True  # Set to True to use cached data, False to fetch fresh data
leagues = ["UEFA Champions League"]
last_year = current_year + 1 if f"{str(current_year)}-{str(current_year+1)[2:]}" 
seasons = [f"{str(year)}-{str(year+1)[2:]}" for year in range(1992, current_year+1)]
if get_current_season_only:
    current_season_cl = f"{current_year}-{str(current_year+1)[2:]}"
    seasons = [current_season_cl] if current_season_cl in seasons else []
fbref = sd.FBref(leagues=leagues, seasons=seasons)
ucl_schedule = fbref.read_schedule(force_cache=use_cache) if seasons else None
ucl_schedule = ucl_schedule.reset_index() if ucl_schedule is not None else None

[05/31/25 15:40:54] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=633091;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=754279;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>

/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

KeyError: '2526'

In [ ]:
ucl_schedule

In [2]:
import os
os.getenv('SOCCERDATA_DIR')

'lib/soccerdata'

In [ ]:
fbref = sd.FBref()
leagues_df = fbref.read_leagues()
leagues_df

[05/31/25 16:28:10] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=444035;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=357918;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

                    INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=640053;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=378708;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#291\291]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>

/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

,gender,governing_body,first_season,last_season,tier,awards,url,country
league,,,,,,,,
Big 5 European Leagues Combined,M,<NA>,9596,2425,1st,<NA>,/en/comps/Big5/history/Big-5-European-Leagues-...,<NA>
ENG-Premier League,M,<NA>,8889,2425,1st,"Premier League Golden Boot, Premier League Gol...",/en/comps/9/history/Premier-League-Seasons,ENG
ESP-La Liga,M,<NA>,8889,2425,1st,"La Liga Best Player, Trofeo Alfredo Di Stéfano",/en/comps/12/history/La-Liga-Seasons,ESP
FRA-Ligue 1,M,<NA>,9596,2425,1st,Ligue 1 Male Player of the Year,/en/comps/13/history/Ligue-1-Seasons,FRA
GER-Bundesliga,M,<NA>,8889,2425,1st,<NA>,/en/comps/20/history/Bundesliga-Seasons,GER
INT-European Championships,M,UEFA,0001,2425,1st,<NA>,/en/comps/676/history/UEFA-Euro-Seasons,<NA>
INT-Women's World Cup,F,FIFA,9192,2324,1st,"FIFA Women's World Cup All-Star Team, FIFA Wom...",/en/comps/106/history/Womens-World-Cup-Seasons,<NA>
INT-World Cup,M,FIFA,3031,2223,1st,"FIFA World Cup All-Star Team, FIFA World Cup B...",/en/comps/1/history/World-Cup-Seasons,<NA>
ITA-Serie A,M,<NA>,8889,2425,1st,"Serie A Footballer of the Year, Serie A Italia...",/en/comps/11/history/Serie-A-Seasons,ITA
UEFA Champions League,M,UEFA,9091,2425,1st,<NA>,/en/comps/8/history/Champions-League-Seasons,<NA>

In [4]:
fbref = sd.FBref()
leagues = fbref.read_seasons()
leagues

[05/31/25 16:28:49] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=756520;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=520308;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

                    INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=540476;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=981990;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#291\291]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>

/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

[05/31/25 16:28:52] ERROR    Error while scraping                                                    ]8;id=870298;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=192782;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons.
                             Retrying... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url:
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons

[05/31/25 16:28:55] ERROR    Error while scraping                                                    ]8;id=67341;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=915595;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons.
                             Retrying... (attempt 2 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url:
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons

[05/31/25 16:28:58] ERROR    Error while scraping                                                    ]8;id=778333;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=588321;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#361\361]8;;\
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons.
                             Retrying... (attempt 3 of 5).
                             Traceback (most recent call last):
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/soccerdata/_common.py", line 341, in _download_and_save
                                 response.raise_for_status()
                               File
                             "/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/sit
                             e-packages/requests/models.py", line 1024, in raise_for_status
                                 raise HTTPError(http_error_msg, response=self)
                             requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for
                             url:
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons

KeyboardInterrupt:

In [4]:
seasons = ["2024-25"]
leagues = ["UEFA Champions League"]
fbref = sd.FBref(leagues=leagues, seasons=seasons)
df = fbref.read_schedule(force_cache=True)

[05/31/25 15:33:31] INFO     Saving cached data to lib/soccerdata/data/FBref                          ]8;id=701953;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=367392;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/_common.py#92\92]8;;\

<_io.BufferedReader name='lib/soccerdata/data/FBref/leagues.html'>

/Users/huggingfaceit/code/SoccerBetMLOptimizer/venv/lib/python3.10/site-packages/soccerdata/fbref.py:150: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(dfs)

In [5]:
df.sort_values(by=["date"], ascending=False)

                                                                            round  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                     Final
                             2025-05-07 Paris S-G-Arsenal             Semi-finals
                             2025-05-06 Inter-Barcelona               Semi-finals
                             2025-04-30 Barcelona-Inter               Semi-finals
                             2025-04-29 Arsenal-Paris S-G             Semi-finals
...                                                                           ...
                             2024-09-17 Milan-Liverpool              League phase
                             2024-09-17 Juventus-PSV Eindhoven       League phase
                             2024-09-17 Sporting CP-Lille            League phase
                             2024-09-17 Young Boys-Aston Villa       League phase
                             2024-09-17 Bayern Munich-Dinamo Zagreb  League phase

                                                                     week  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter              <NA>
                             2025-05-07 Paris S-G-Arsenal            <NA>
                             2025-05-06 Inter-Barcelona              <NA>
                             2025-04-30 Barcelona-Inter              <NA>
                             2025-04-29 Arsenal-Paris S-G            <NA>
...                                                                   ...
                             2024-09-17 Milan-Liverpool                 1
                             2024-09-17 Juventus-PSV Eindhoven          1
                             2024-09-17 Sporting CP-Lille               1
                             2024-09-17 Young Boys-Aston Villa          1
                             2024-09-17 Bayern Munich-Dinamo Zagreb     1

                                                                     day  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter              Sat
                             2025-05-07 Paris S-G-Arsenal            Wed
                             2025-05-06 Inter-Barcelona              Tue
                             2025-04-30 Barcelona-Inter              Wed
                             2025-04-29 Arsenal-Paris S-G            Tue
...                                                                  ...
                             2024-09-17 Milan-Liverpool              Tue
                             2024-09-17 Juventus-PSV Eindhoven       Tue
                             2024-09-17 Sporting CP-Lille            Tue
                             2024-09-17 Young Boys-Aston Villa       Tue
                             2024-09-17 Bayern Munich-Dinamo Zagreb  Tue

                                                                          date  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter             2025-05-31
                             2025-05-07 Paris S-G-Arsenal           2025-05-07
                             2025-05-06 Inter-Barcelona             2025-05-06
                             2025-04-30 Barcelona-Inter             2025-04-30
                             2025-04-29 Arsenal-Paris S-G           2025-04-29
...                                                                        ...
                             2024-09-17 Milan-Liverpool             2024-09-17
                             2024-09-17 Juventus-PSV Eindhoven      2024-09-17
                             2024-09-17 Sporting CP-Lille           2024-09-17
                             2024-09-17 Young Boys-Aston Villa      2024-09-17
                             2024-09-17 Bayern Munich-Dinamo Zagreb 2024-09-17

                                                                      time  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter              21:00
                             2025-05-07 Paris S-G-Arsenal            21:00
                             2025-05-06 Inter-Barcelona              21:00
                             2025-04-30 Barcelona-Inter              21:00
                             2025-04-29 Arsenal-Paris S-G            20:00
...                                                                    ...
                             2024-09-17 Milan-Liverpool              21:00
                             2024-09-17 Juventus-PSV Eindhoven       18:45
                             2024-09-17 Sporting CP-Lille            20:00
                             2024-09-17 Young Boys-Aston Villa       18:45
                             2024-09-17 Bayern Munich-Dinamo Zagreb  21:00

                                                                         home_team  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                  Paris S-G
                             2025-05-07 Paris S-G-Arsenal                Paris S-G
                             2025-05-06 Inter-Barcelona                      Inter
                             2025-04-30 Barcelona-Inter                  Barcelona
                             2025-04-29 Arsenal-Paris S-G                  Arsenal
...                                                                            ...
                             2024-09-17 Milan-Liverpool                      Milan
                             2024-09-17 Juventus-PSV Eindhoven            Juventus
                             2024-09-17 Sporting CP-Lille              Sporting CP
                             2024-09-17 Young Boys-Aston Villa          Young Boys
                             2024-09-17 Bayern Munich-Dinamo Zagreb  Bayern Munich

                                                                     home_xg  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                 <NA>
                             2025-05-07 Paris S-G-Arsenal                1.7
                             2025-05-06 Inter-Barcelona                  2.2
                             2025-04-30 Barcelona-Inter                  1.4
                             2025-04-29 Arsenal-Paris S-G                1.7
...                                                                      ...
                             2024-09-17 Milan-Liverpool                  0.6
                             2024-09-17 Juventus-PSV Eindhoven           2.9
                             2024-09-17 Sporting CP-Lille                1.6
                             2024-09-17 Young Boys-Aston Villa           0.6
                             2024-09-17 Bayern Munich-Dinamo Zagreb      5.9

                                                                    score  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter              <NA>
                             2025-05-07 Paris S-G-Arsenal             2–1
                             2025-05-06 Inter-Barcelona               4–3
                             2025-04-30 Barcelona-Inter               3–3
                             2025-04-29 Arsenal-Paris S-G             0–1
...                                                                   ...
                             2024-09-17 Milan-Liverpool               1–3
                             2024-09-17 Juventus-PSV Eindhoven        3–1
                             2024-09-17 Sporting CP-Lille             2–0
                             2024-09-17 Young Boys-Aston Villa        0–3
                             2024-09-17 Bayern Munich-Dinamo Zagreb   9–2

                                                                     away_xg  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                 <NA>
                             2025-05-07 Paris S-G-Arsenal                2.8
                             2025-05-06 Inter-Barcelona                  2.8
                             2025-04-30 Barcelona-Inter                  0.8
                             2025-04-29 Arsenal-Paris S-G                1.2
...                                                                      ...
                             2024-09-17 Milan-Liverpool                  3.1
                             2024-09-17 Juventus-PSV Eindhoven           1.0
                             2024-09-17 Sporting CP-Lille                0.4
                             2024-09-17 Young Boys-Aston Villa           2.0
                             2024-09-17 Bayern Munich-Dinamo Zagreb      0.7

                                                                         away_team  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                      Inter
                             2025-05-07 Paris S-G-Arsenal                  Arsenal
                             2025-05-06 Inter-Barcelona                  Barcelona
                             2025-04-30 Barcelona-Inter                      Inter
                             2025-04-29 Arsenal-Paris S-G                Paris S-G
...                                                                            ...
                             2024-09-17 Milan-Liverpool                  Liverpool
                             2024-09-17 Juventus-PSV Eindhoven       PSV Eindhoven
                             2024-09-17 Sporting CP-Lille                    Lille
                             2024-09-17 Young Boys-Aston Villa         Aston Villa
                             2024-09-17 Bayern Munich-Dinamo Zagreb  Dinamo Zagreb

                                                                     attendance  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                    <NA>
                             2025-05-07 Paris S-G-Arsenal                 47511
                             2025-05-06 Inter-Barcelona                   75504
                             2025-04-30 Barcelona-Inter                   50314
                             2025-04-29 Arsenal-Paris S-G                 59664
...                                                                         ...
                             2024-09-17 Milan-Liverpool                   59826
                             2024-09-17 Juventus-PSV Eindhoven            40417
                             2024-09-17 Sporting CP-Lille                 40024
                             2024-09-17 Young Boys-Aston Villa            31500
                             2024-09-17 Bayern Munich-Dinamo Zagreb       75000

                                                                                             venue  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                              Allianz Arena
                             2025-05-07 Paris S-G-Arsenal                         Parc des Princes
                             2025-05-06 Inter-Barcelona                     Stadio Giuseppe Meazza
                             2025-04-30 Barcelona-Inter              Estadi Olímpic Lluís Companys
                             2025-04-29 Arsenal-Paris S-G                         Emirates Stadium
...                                                                                            ...
                             2024-09-17 Milan-Liverpool                     Stadio Giuseppe Meazza
                             2024-09-17 Juventus-PSV Eindhoven                     Allianz Stadium
                             2024-09-17 Sporting CP-Lille                    Estádio José Alvalade
                             2024-09-17 Young Boys-Aston Villa                    Stadion Wankdorf
                             2024-09-17 Bayern Munich-Dinamo Zagreb                  Allianz Arena

                                                                                 referee  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                             <NA>
                             2025-05-07 Paris S-G-Arsenal                   Felix Zwayer
                             2025-05-06 Inter-Barcelona                 Szymon Marciniak
                             2025-04-30 Barcelona-Inter                   Clément Turpin
                             2025-04-29 Arsenal-Paris S-G                  Slavko Vinčič
...                                                                                  ...
                             2024-09-17 Milan-Liverpool                      Espen Eskås
                             2024-09-17 Juventus-PSV Eindhoven       Alejandro Hernández
                             2024-09-17 Sporting CP-Lille                 Donatas Rumšas
                             2024-09-17 Young Boys-Aston Villa            Georgi Kabakov
                             2024-09-17 Bayern Munich-Dinamo Zagreb        Juan Martínez

                                                                                                          match_report  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                                                           None
                             2025-05-07 Paris S-G-Arsenal            /en/matches/a73bdd5b/Paris-Saint-Germain-Arsen...
                             2025-05-06 Inter-Barcelona              /en/matches/ff6aaaa9/Internazionale-Barcelona-...
                             2025-04-30 Barcelona-Inter              /en/matches/4b3ea62f/Barcelona-Internazionale-...
                             2025-04-29 Arsenal-Paris S-G            /en/matches/d85808e6/Arsenal-Paris-Saint-Germa...
...                                                                                                                ...
                             2024-09-17 Milan-Liverpool              /en/matches/54ed5557/Milan-Liverpool-September...
                             2024-09-17 Juventus-PSV Eindhoven       /en/matches/931cd5fb/Juventus-PSV-Eindhoven-Se...
                             2024-09-17 Sporting CP-Lille            /en/matches/aaca158d/Sporting-CP-Lille-Septemb...
                             2024-09-17 Young Boys-Aston Villa       /en/matches/568274fc/Young-Boys-Aston-Villa-Se...
                             2024-09-17 Bayern Munich-Dinamo Zagreb  /en/matches/7c5c2955/Bayern-Munich-Dinamo-Zagr...

                                                                                                          notes  \
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                                                    <NA>
                             2025-05-07 Paris S-G-Arsenal                             Leg 2 of 2; Paris S-G won
                             2025-05-06 Inter-Barcelona              Leg 2 of 2; Inter won; Required Extra Time
                             2025-04-30 Barcelona-Inter                                              Leg 1 of 2
                             2025-04-29 Arsenal-Paris S-G                                            Leg 1 of 2
...                                                                                                         ...
                             2024-09-17 Milan-Liverpool                                                    <NA>
                             2024-09-17 Juventus-PSV Eindhoven                                             <NA>
                             2024-09-17 Sporting CP-Lille                                                  <NA>
                             2024-09-17 Young Boys-Aston Villa                                             <NA>
                             2024-09-17 Bayern Munich-Dinamo Zagreb                                        <NA>

                                                                      game_id
league                season game
UEFA Champions League 2425   2025-05-31 Paris S-G-Inter                   NaN
                             2025-05-07 Paris S-G-Arsenal            a73bdd5b
                             2025-05-06 Inter-Barcelona              ff6aaaa9
                             2025-04-30 Barcelona-Inter              4b3ea62f
                             2025-04-29 Arsenal-Paris S-G            d85808e6
...                                                                       ...
                             2024-09-17 Milan-Liverpool              54ed5557
                             2024-09-17 Juventus-PSV Eindhoven       931cd5fb
                             2024-09-17 Sporting CP-Lille            aaca158d
                             2024-09-17 Young Boys-Aston Villa       568274fc
                             2024-09-17 Bayern Munich-Dinamo Zagreb  7c5c2955

[189 rows x 16 columns]

In [8]:
seasons = [f"{str(year)}-{str(year+1)[2:]}" for year in range(1930, 2024, 4)]
[seasons.remove(f"{str(year)}-{str(year+1)[2:]}") for year in range(1942, 1948, 4)]
fbref = sd.FBref(leagues="INT-World Cup", seasons=seasons)
fbref.read_schedule(force_cache=True)

[06/06/24 15:08:39] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=462976;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=870866;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:686: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(schedule)

                                                                      round  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal                  Group stage
                     2002-06-01 Germany-Saudi Arabia            Group stage
                     2002-06-01 Rep. of Ireland-Cameroon        Group stage
                     2002-06-01 Uruguay-Denmark                 Group stage
                     2002-06-02 Argentina-Nigeria               Group stage
...                                                                     ...
              9899   1998-07-04 Netherlands-Argentina        Quarter-finals
                     1998-07-07 Brazil-Netherlands              Semi-finals
                     1998-07-08 France-Croatia                  Semi-finals
                     1998-07-11 Netherlands-Croatia       Third-place match
                     1998-07-12 Brazil-France                         Final

                                                          day       date  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal            Fri 2002-05-31
                     2002-06-01 Germany-Saudi Arabia      Sat 2002-06-01
                     2002-06-01 Rep. of Ireland-Cameroon  Sat 2002-06-01
                     2002-06-01 Uruguay-Denmark           Sat 2002-06-01
                     2002-06-02 Argentina-Nigeria         Sun 2002-06-02
...                                                       ...        ...
              9899   1998-07-04 Netherlands-Argentina     Sat 1998-07-04
                     1998-07-07 Brazil-Netherlands        Tue 1998-07-07
                     1998-07-08 France-Croatia            Wed 1998-07-08
                     1998-07-11 Netherlands-Croatia       Sat 1998-07-11
                     1998-07-12 Brazil-France             Sun 1998-07-12

                                                           time  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal            20:30
                     2002-06-01 Germany-Saudi Arabia      20:30
                     2002-06-01 Rep. of Ireland-Cameroon  15:30
                     2002-06-01 Uruguay-Denmark           18:00
                     2002-06-02 Argentina-Nigeria         14:30
...                                                         ...
              9899   1998-07-04 Netherlands-Argentina     16:30
                     1998-07-07 Brazil-Netherlands        21:00
                     1998-07-08 France-Croatia            21:00
                     1998-07-11 Netherlands-Croatia       21:00
                     1998-07-12 Brazil-France             21:00

                                                                home_team  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal                     France
                     2002-06-01 Germany-Saudi Arabia              Germany
                     2002-06-01 Rep. of Ireland-Cameroon  Rep. of Ireland
                     2002-06-01 Uruguay-Denmark                   Uruguay
                     2002-06-02 Argentina-Nigeria               Argentina
...                                                                   ...
              9899   1998-07-04 Netherlands-Argentina         Netherlands
                     1998-07-07 Brazil-Netherlands                 Brazil
                     1998-07-08 France-Croatia                     France
                     1998-07-11 Netherlands-Croatia           Netherlands
                     1998-07-12 Brazil-France                      Brazil

                                                                score  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal                    0–1
                     2002-06-01 Germany-Saudi Arabia              8–0
                     2002-06-01 Rep. of Ireland-Cameroon          1–1
                     2002-06-01 Uruguay-Denmark                   1–2
                     2002-06-02 Argentina-Nigeria                 1–0
...                                                               ...
              9899   1998-07-04 Netherlands-Argentina             2–1
                     1998-07-07 Brazil-Netherlands        (4) 1–1 (2)
                     1998-07-08 France-Croatia                    2–1
                     1998-07-11 Netherlands-Croatia               1–2
                     1998-07-12 Brazil-France                     0–3

                                                             away_team  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal                 Senegal
                     2002-06-01 Germany-Saudi Arabia      Saudi Arabia
                     2002-06-01 Rep. of Ireland-Cameroon      Cameroon
                     2002-06-01 Uruguay-Denmark                Denmark
                     2002-06-02 Argentina-Nigeria              Nigeria
...                                                                ...
              9899   1998-07-04 Netherlands-Argentina        Argentina
                     1998-07-07 Brazil-Netherlands         Netherlands
                     1998-07-08 France-Croatia                 Croatia
                     1998-07-11 Netherlands-Croatia            Croatia
                     1998-07-12 Brazil-France                   France

                                                          attendance  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal                 62561
                     2002-06-01 Germany-Saudi Arabia           32218
                     2002-06-01 Rep. of Ireland-Cameroon       33679
                     2002-06-01 Uruguay-Denmark                30157
                     2002-06-02 Argentina-Nigeria              34050
...                                                              ...
              9899   1998-07-04 Netherlands-Argentina          60000
                     1998-07-07 Brazil-Netherlands             60000
                     1998-07-08 France-Croatia                 80000
                     1998-07-11 Netherlands-Croatia            44000
                     1998-07-12 Brazil-France                  80000

                                                                                           venue  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal            Seoul World Cup Stadium (Neutral Site)
                     2002-06-01 Germany-Saudi Arabia                 Sapporo Dome (Neutral Site)
                     2002-06-01 Rep. of Ireland-Cameroon   Denka Big Swan Stadium (Neutral Site)
                     2002-06-01 Uruguay-Denmark                 Munsu Cup Stadium (Neutral Site)
                     2002-06-02 Argentina-Nigeria          Kashima Soccer Stadium (Neutral Site)
...                                                                                          ...
              9899   1998-07-04 Netherlands-Argentina            Orange Vélodrome (Neutral Site)
                     1998-07-07 Brazil-Netherlands               Orange Vélodrome (Neutral Site)
                     1998-07-08 France-Croatia                    Stade de France (Neutral Site)
                     1998-07-11 Netherlands-Croatia              Parc des Princes (Neutral Site)
                     1998-07-12 Brazil-France                     Stade de France (Neutral Site)

                                                         referee  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal              <NA>
                     2002-06-01 Germany-Saudi Arabia        <NA>
                     2002-06-01 Rep. of Ireland-Cameroon    <NA>
                     2002-06-01 Uruguay-Denmark             <NA>
                     2002-06-02 Argentina-Nigeria           <NA>
...                                                          ...
              9899   1998-07-04 Netherlands-Argentina       <NA>
                     1998-07-07 Brazil-Netherlands          <NA>
                     1998-07-08 France-Croatia              <NA>
                     1998-07-11 Netherlands-Croatia         <NA>
                     1998-07-12 Brazil-France               <NA>

                                                                                               match_report  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal            /en/matches/df429f29/France-Senegal-May-31-200...
                     2002-06-01 Germany-Saudi Arabia      /en/matches/8044bc39/Germany-Saudi-Arabia-June...
                     2002-06-01 Rep. of Ireland-Cameroon  /en/matches/a8e32cf4/Republic-of-Ireland-Camer...
                     2002-06-01 Uruguay-Denmark           /en/matches/43a72224/Uruguay-Denmark-June-1-20...
                     2002-06-02 Argentina-Nigeria         /en/matches/0a576ae4/Argentina-Nigeria-June-2-...
...                                                                                                     ...
              9899   1998-07-04 Netherlands-Argentina     /en/matches/aa1bb817/Netherlands-Argentina-Jul...
                     1998-07-07 Brazil-Netherlands        /en/matches/e1ac3cbb/Brazil-Netherlands-July-7...
                     1998-07-08 France-Croatia            /en/matches/169a83e4/France-Croatia-July-8-199...
                     1998-07-11 Netherlands-Croatia       /en/matches/c52d688b/Netherlands-Croatia-July-...
                     1998-07-12 Brazil-France             /en/matches/a9fd46f1/Brazil-France-July-12-199...

                                                                                                     notes  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal                                                        <NA>
                     2002-06-01 Germany-Saudi Arabia                                                  <NA>
                     2002-06-01 Rep. of Ireland-Cameroon                                              <NA>
                     2002-06-01 Uruguay-Denmark                                                       <NA>
                     2002-06-02 Argentina-Nigeria                                                     <NA>
...                                                                                                    ...
              9899   1998-07-04 Netherlands-Argentina                                                 <NA>
                     1998-07-07 Brazil-Netherlands        Brazil won on penalty kicks following extra time
                     1998-07-08 France-Croatia                                                        <NA>
                     1998-07-11 Netherlands-Croatia                                                   <NA>
                     1998-07-12 Brazil-France                                                         <NA>

                                                          week  home_xg  \
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal               1     <NA>
                     2002-06-01 Germany-Saudi Arabia         1     <NA>
                     2002-06-01 Rep. of Ireland-Cameroon     1     <NA>
                     2002-06-01 Uruguay-Denmark              1     <NA>
                     2002-06-02 Argentina-Nigeria            1     <NA>
...                                                        ...      ...
              9899   1998-07-04 Netherlands-Argentina     <NA>     <NA>
                     1998-07-07 Brazil-Netherlands        <NA>     <NA>
                     1998-07-08 France-Croatia            <NA>     <NA>
                     1998-07-11 Netherlands-Croatia       <NA>     <NA>
                     1998-07-12 Brazil-France             <NA>     <NA>

                                                          away_xg   game_id
league        season game
INT-World Cup 0203   2002-05-31 France-Senegal               <NA>  df429f29
                     2002-06-01 Germany-Saudi Arabia         <NA>  8044bc39
                     2002-06-01 Rep. of Ireland-Cameroon     <NA>  a8e32cf4
                     2002-06-01 Uruguay-Denmark              <NA>  43a72224
                     2002-06-02 Argentina-Nigeria            <NA>  0a576ae4
...                                                           ...       ...
              9899   1998-07-04 Netherlands-Argentina        <NA>  aa1bb817
                     1998-07-07 Brazil-Netherlands           <NA>  e1ac3cbb
                     1998-07-08 France-Croatia               <NA>  169a83e4
                     1998-07-11 Netherlands-Croatia          <NA>  c52d688b
                     1998-07-12 Brazil-France                <NA>  a9fd46f1

[964 rows x 16 columns]

In [10]:
seasons = [f"{str(year)[2:]}-{str(year+1)[2:]}" for year in range(1930, 2025)]
[seasons.remove(f"{str(year)[2:]}-{str(year+1)[2:]}") for year in range(1939, 1946)]
fbref = sd.FBref(leagues="Big 5 European Leagues Combined", seasons=seasons)
big5 = fbref.read_schedule(force_cache=True)

[06/06/24 15:10:27] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=389164;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=722149;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:686: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(schedule)

In [14]:
big5.reset_index(inplace=True)

In [15]:
big5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86027 entries, 0 to 86026
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   league        86027 non-null  object
 1   season        86027 non-null  object
 2   game          86027 non-null  object
 3   week          85994 non-null  Int64
 4   day           86027 non-null  string
 5   date          86027 non-null  datetime64[ns]
 6   time          18146 non-null  string
 7   home_team     86027 non-null  string
 8   score         85926 non-null  string
 9   away_team     86027 non-null  string
 10  attendance    24024 non-null  Int64
 11  venue         43702 non-null  string
 12  referee       60311 non-null  string
 13  match_report  86027 non-null  object
 14  notes         146 non-null    string
 15  round         5679 non-null   string
 16  home_xg       12606 non-null  Float64
 17  away_xg       12606 non-null  Float64
 18  game_id       86027 non-null  object
dtypes: Float64(2), Int64(2), datetime64[ns](1), object(5), string(9)
memory usage: 12.8+ MB

In [13]:
big5.head()

                                                                   week  day  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City     1  Sat
                          2000-08-19 Chelsea-West Ham                 1  Sat
                          2000-08-19 Coventry City-Middlesbrough      1  Sat
                          2000-08-19 Derby County-Southampton         1  Sat
                          2000-08-19 Leeds United-Everton             1  Sat

                                                                        date  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City 2000-08-19
                          2000-08-19 Chelsea-West Ham             2000-08-19
                          2000-08-19 Coventry City-Middlesbrough  2000-08-19
                          2000-08-19 Derby County-Southampton     2000-08-19
                          2000-08-19 Leeds United-Everton         2000-08-19

                                                                   time  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City  <NA>
                          2000-08-19 Chelsea-West Ham              <NA>
                          2000-08-19 Coventry City-Middlesbrough   <NA>
                          2000-08-19 Derby County-Southampton      <NA>
                          2000-08-19 Leeds United-Everton          <NA>

                                                                       home_team  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City   Charlton Ath
                          2000-08-19 Chelsea-West Ham                    Chelsea
                          2000-08-19 Coventry City-Middlesbrough   Coventry City
                          2000-08-19 Derby County-Southampton       Derby County
                          2000-08-19 Leeds United-Everton           Leeds United

                                                                  score  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City   4–0
                          2000-08-19 Chelsea-West Ham               4–2
                          2000-08-19 Coventry City-Middlesbrough    1–3
                          2000-08-19 Derby County-Southampton       2–2
                          2000-08-19 Leeds United-Everton           2–0

                                                                         away_team  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City  Manchester City
                          2000-08-19 Chelsea-West Ham                     West Ham
                          2000-08-19 Coventry City-Middlesbrough     Middlesbrough
                          2000-08-19 Derby County-Southampton          Southampton
                          2000-08-19 Leeds United-Everton                  Everton

                                                                   attendance  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City       20043
                          2000-08-19 Chelsea-West Ham                   34914
                          2000-08-19 Coventry City-Middlesbrough        20624
                          2000-08-19 Derby County-Southampton           27223
                          2000-08-19 Leeds United-Everton               40010

                                                                             venue  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City       The Valley
                          2000-08-19 Chelsea-West Ham              Stamford Bridge
                          2000-08-19 Coventry City-Middlesbrough    Highfield Road
                          2000-08-19 Derby County-Southampton           Pride Park
                          2000-08-19 Leeds United-Everton              Elland Road

                                                                            referee  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City        Rob Harris
                          2000-08-19 Chelsea-West Ham                 Graham Barber
                          2000-08-19 Coventry City-Middlesbrough       Barry Knight
                          2000-08-19 Derby County-Southampton           Andy D'Urso
                          2000-08-19 Leeds United-Everton          Dermot Gallagher

                                                                                                        match_report  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City  /en/matches/d9b84fe5/Charlton-Athletic-Manches...
                          2000-08-19 Chelsea-West Ham              /en/matches/7c440c56/Chelsea-West-Ham-United-A...
                          2000-08-19 Coventry City-Middlesbrough   /en/matches/812d0818/Coventry-City-Middlesbrou...
                          2000-08-19 Derby County-Southampton      /en/matches/b584dafa/Derby-County-Southampton-...
                          2000-08-19 Leeds United-Everton          /en/matches/12b9d2dd/Leeds-United-Everton-Augu...

                                                                  notes round  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City  <NA>  <NA>
                          2000-08-19 Chelsea-West Ham              <NA>  <NA>
                          2000-08-19 Coventry City-Middlesbrough   <NA>  <NA>
                          2000-08-19 Derby County-Southampton      <NA>  <NA>
                          2000-08-19 Leeds United-Everton          <NA>  <NA>

                                                                   home_xg  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City     <NA>
                          2000-08-19 Chelsea-West Ham                 <NA>
                          2000-08-19 Coventry City-Middlesbrough      <NA>
                          2000-08-19 Derby County-Southampton         <NA>
                          2000-08-19 Leeds United-Everton             <NA>

                                                                   away_xg  \
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City     <NA>
                          2000-08-19 Chelsea-West Ham                 <NA>
                          2000-08-19 Coventry City-Middlesbrough      <NA>
                          2000-08-19 Derby County-Southampton         <NA>
                          2000-08-19 Leeds United-Everton             <NA>

                                                                    game_id
league             season game
ENG-Premier League 0001   2000-08-19 Charlton Ath-Manchester City  d9b84fe5
                          2000-08-19 Chelsea-West Ham              7c440c56
                          2000-08-19 Coventry City-Middlesbrough   812d0818
                          2000-08-19 Derby County-Southampton      b584dafa
                          2000-08-19 Leeds United-Everton          12b9d2dd

In [19]:
fbref = sd.FBref()
player_match_stats = fbref.read_player_match_stats(stat_type="passing", match_id='db261cb0', force_cache=True)
player_match_stats.columns

[06/07/24 10:31:26] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=572805;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=580519;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

                    INFO     No seasons provided. Will retrieve data for the last 5 seasons.         ]8;id=863924;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=803192;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#291\291]8;;\

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py:493: UserWarning: Season id "2021" is ambiguous: interpreting as "20-21"
  warnings.warn(msg, stacklevel=1)
c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:686: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(schedule)

[06/07/24 10:31:33] INFO     [1/1] Retrieving game with id=db261cb0                                    ]8;id=905138;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=326284;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py#802\802]8;;\

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:813: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to ".//table[@id='stats_47c64c55_passing']"
  html_table = tree.find("//table[@id='" + id_format.format(home_team["id"]) + "']")
c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:824: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to ".//table[@id='stats_33c895d4_passing']"
  html_table = tree.find("//table[@id='" + id_format.format(away_team["id"]) + "']")

MultiIndex([('jersey_number',        ''),
            (       'nation',        ''),
            (          'pos',        ''),
            (          'age',        ''),
            (          'min',        ''),
            (        'Total',     'Cmp'),
            (        'Total',     'Att'),
            (        'Total',    'Cmp%'),
            (        'Total', 'TotDist'),
            (        'Total', 'PrgDist'),
            (        'Short',     'Cmp'),
            (        'Short',     'Att'),
            (        'Short',    'Cmp%'),
            (       'Medium',     'Cmp'),
            (       'Medium',     'Att'),
            (       'Medium',    'Cmp%'),
            (         'Long',     'Cmp'),
            (         'Long',     'Att'),
            (         'Long',    'Cmp%'),
            (          'Ast',        ''),
            (          'xAG',        ''),
            (           'xA',        ''),
            (           'KP',        ''),
            (          '1/3',        ''),
            (          'PPA',        ''),
            (        'CrsPA',        ''),
            (         'PrgP',        ''),
            (      'game_id',        '')],
           )

In [32]:
player_match_stats = fbref.read_player_match_stats(stat_type="summary", match_id='db261cb0', force_cache=True)
player_match_stats

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py:493: UserWarning: Season id "2021" is ambiguous: interpreting as "20-21"
  warnings.warn(msg, stacklevel=1)
c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:686: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(schedule)

[06/07/24 10:46:50] INFO     [1/1] Retrieving game with id=db261cb0                                    ]8;id=887760;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=558362;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py#802\802]8;;\

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:813: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to ".//table[@id='stats_47c64c55_summary']"
  html_table = tree.find("//table[@id='" + id_format.format(home_team["id"]) + "']")
c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:824: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to ".//table[@id='stats_33c895d4_summary']"
  html_table = tree.find("//table[@id='" + id_format.format(away_team["id"]) + "']")

                                                                                                  jersey_number  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend               10
                                                                               Cheikhou Kouyaté               8
                                                                               Eberechi Eze                  25
                                                                               James McArthur                18
                                                                               James McCarthy                22
                                                                               Jeffrey Schlupp               15
                                                                               Joel Ward                      2
                                                                               Jordan Ayew                    9
                                                                               Luka Milivojević               4
                                                                               Scott Dann                     6
                                                                               Tyrick Mitchell               27
                                                                               Vicente Guaita                31
                                                                               Wilfried Zaha                 11
                                                                Southampton    Alex McCarthy                  1
                                                                               Che Adams                     10
                                                                               Danny Ings                     9
                                                                               Jack Stephens                  5
                                                                               James Ward-Prowse              8
                                                                               Jan Bednarek                  35
                                                                               Jannik Vestergaard             4
                                                                               Kyle Walker-Peters             2
                                                                               Moussa Djenepo                12
                                                                               Nathan Redmond                11
                                                                               Oriol Romeu                    6
                                                                               Ryan Bertrand                  3
                                                                               Shane Long                     7
                                                                               William Smallbone             20

                                                                                                  nation  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend       ENG
                                                                               Cheikhou Kouyaté      SEN
                                                                               Eberechi Eze          ENG
                                                                               James McArthur        SCO
                                                                               James McCarthy        IRL
                                                                               Jeffrey Schlupp       GHA
                                                                               Joel Ward             ENG
                                                                               Jordan Ayew           GHA
                                                                               Luka Milivojević      SRB
                                                                               Scott Dann            ENG
                                                                               Tyrick Mitchell       ENG
                                                                               Vicente Guaita        ESP
                                                                               Wilfried Zaha         CIV
                                                                Southampton    Alex McCarthy         ENG
                                                                               Che Adams             SCO
                                                                               Danny Ings            ENG
                                                                               Jack Stephens         ENG
                                                                               James Ward-Prowse     ENG
                                                                               Jan Bednarek          POL
                                                                               Jannik Vestergaard    DEN
                                                                               Kyle Walker-Peters    ENG
                                                                               Moussa Djenepo        MLI
                                                                               Nathan Redmond        ENG
                                                                               Oriol Romeu           ESP
                                                                               Ryan Bertrand         ENG
                                                                               Shane Long            IRL
                                                                               William Smallbone     IRL

                                                                                                  pos  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend     RM
                                                                               Cheikhou Kouyaté    CB
                                                                               Eberechi Eze        LM
                                                                               James McArthur      CM
                                                                               James McCarthy      CM
                                                                               Jeffrey Schlupp     LM
                                                                               Joel Ward           RB
                                                                               Jordan Ayew         FW
                                                                               Luka Milivojević    CM
                                                                               Scott Dann          CB
                                                                               Tyrick Mitchell     LB
                                                                               Vicente Guaita      GK
                                                                               Wilfried Zaha       FW
                                                                Southampton    Alex McCarthy       GK
                                                                               Che Adams           FW
                                                                               Danny Ings          FW
                                                                               Jack Stephens       CB
                                                                               James Ward-Prowse   CM
                                                                               Jan Bednarek        CB
                                                                               Jannik Vestergaard  CB
                                                                               Kyle Walker-Peters  RB
                                                                               Moussa Djenepo      RM
                                                                               Nathan Redmond      LM
                                                                               Oriol Romeu         CM
                                                                               Ryan Bertrand       LB
                                                                               Shane Long          FW
                                                                               William Smallbone   RM

                                                                                                      age  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend     29-058
                                                                               Cheikhou Kouyaté    30-266
                                                                               Eberechi Eze        22-075
                                                                               James McArthur      32-341
                                                                               James McCarthy      29-305
                                                                               Jeffrey Schlupp     27-264
                                                                               Joel Ward           30-319
                                                                               Jordan Ayew         29-001
                                                                               Luka Milivojević    29-158
                                                                               Scott Dann          33-211
                                                                               Tyrick Mitchell     21-011
                                                                               Vicente Guaita      33-246
                                                                               Wilfried Zaha       27-307
                                                                Southampton    Alex McCarthy       30-284
                                                                               Che Adams           24-061
                                                                               Danny Ings          28-051
                                                                               Jack Stephens       26-229
                                                                               James Ward-Prowse   25-316
                                                                               Jan Bednarek        24-153
                                                                               Jannik Vestergaard  28-040
                                                                               Kyle Walker-Peters  23-152
                                                                               Moussa Djenepo      22-089
                                                                               Nathan Redmond      26-190
                                                                               Oriol Romeu         28-354
                                                                               Ryan Bertrand       31-038
                                                                               Shane Long          33-234
                                                                               William Smallbone   20-204

                                                                                                  min  \

league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend     90
                                                                               Cheikhou Kouyaté    90
                                                                               Eberechi Eze        10
                                                                               James McArthur      90
                                                                               James McCarthy      73
                                                                               Jeffrey Schlupp     80
                                                                               Joel Ward           90
                                                                               Jordan Ayew         90
                                                                               Luka Milivojević    17
                                                                               Scott Dann          90
                                                                               Tyrick Mitchell     90
                                                                               Vicente Guaita      90
                                                                               Wilfried Zaha       90
                                                                Southampton    Alex McCarthy       90
                                                                               Che Adams           84
                                                                               Danny Ings          90
                                                                               Jack Stephens       90
                                                                               James Ward-Prowse   90
                                                                               Jan Bednarek        45
                                                                               Jannik Vestergaard  45
                                                                               Kyle Walker-Peters  90
                                                                               Moussa Djenepo      14
                                                                               Nathan Redmond      90
                                                                               Oriol Romeu         90
                                                                               Ryan Bertrand       90
                                                                               Shane Long           6
                                                                               William Smallbone   76

                                                                                                  Performance  \
                                                                                                          Gls
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend              0
                                                                               Cheikhou Kouyaté             0
                                                                               Eberechi Eze                 0
                                                                               James McArthur               0
                                                                               James McCarthy               0
                                                                               Jeffrey Schlupp              0
                                                                               Joel Ward                    0
                                                                               Jordan Ayew                  0
                                                                               Luka Milivojević             0
                                                                               Scott Dann                   0
                                                                               Tyrick Mitchell              0
                                                                               Vicente Guaita               0
                                                                               Wilfried Zaha                1
                                                                Southampton    Alex McCarthy                0
                                                                               Che Adams                    0
                                                                               Danny Ings                   0
                                                                               Jack Stephens                0
                                                                               James Ward-Prowse            0
                                                                               Jan Bednarek                 0
                                                                               Jannik Vestergaard           0
                                                                               Kyle Walker-Peters           0
                                                                               Moussa Djenepo               0
                                                                               Nathan Redmond               0
                                                                               Oriol Romeu                  0
                                                                               Ryan Bertrand                0
                                                                               Shane Long                   0
                                                                               William Smallbone            0

                                                                                                       \
                                                                                                  Ast
league             season game                                  team           player
ENG-Premier League 2021   2020-09-12 Crystal Palace-Southampton Crystal Palace Andros Townsend      1
                                                                               Cheikhou Kouyaté     0
                                                                               Eberechi Eze         0
                                                                               James McArthur       0
                                                                               James McCarthy       0
                                                                               Jeffrey Schlupp      0
                                                                               Joel Ward            0
                                                                               Jordan Ayew          0
                                                                               Luka Milivojević     0
                                                                               Scott Dann           0
                                                                               Tyrick Mitchell      0

In [21]:
player_match_stats.columns.shape

(31,)

In [28]:
player_match_stats.reset_index(inplace=True, drop=True)
player_match_stats.columns

MultiIndex([(      'level_0',        ''),
            (        'index',        ''),
            (       'league',        ''),
            (       'season',        ''),
            (         'game',        ''),
            (         'team',        ''),
            (       'player',        ''),
            ('jersey_number',        ''),
            (       'nation',        ''),
            (          'pos',        ''),
            (          'age',        ''),
            (          'min',        ''),
            (  'Performance',     'Gls'),
            (  'Performance',     'Ast'),
            (  'Performance',      'PK'),
            (  'Performance',   'PKatt'),
            (  'Performance',      'Sh'),
            (  'Performance',     'SoT'),
            (  'Performance',    'CrdY'),
            (  'Performance',    'CrdR'),
            (  'Performance', 'Touches'),
            (  'Performance',     'Tkl'),
            (  'Performance',     'Int'),
            (  'Performance',  'Blocks'),
            (     'Expected',      'xG'),
            (     'Expected',    'npxG'),
            (     'Expected',     'xAG'),
            (          'SCA',     'SCA'),
            (          'SCA',     'GCA'),
            (       'Passes',     'Cmp'),
            (       'Passes',     'Att'),
            (       'Passes',    'Cmp%'),
            (       'Passes',    'PrgP'),
            (      'Carries', 'Carries'),
            (      'Carries',    'PrgC'),
            (     'Take-Ons',     'Att'),
            (     'Take-Ons',    'Succ'),
            (      'game_id',        '')],
           )

In [38]:
player_match_stats = fbref.read_player_match_stats(stat_type="misc", match_id='db261cb0', force_cache=True)
player_match_stats.columns

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py:493: UserWarning: Season id "2021" is ambiguous: interpreting as "20-21"
  warnings.warn(msg, stacklevel=1)
c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:686: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(schedule)

[06/07/24 10:51:40] INFO     [1/1] Retrieving game with id=db261cb0                                    ]8;id=557035;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py\fbref.py]8;;\:]8;id=332299;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py#802\802]8;;\

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:813: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to ".//table[@id='stats_47c64c55_misc']"
  html_table = tree.find("//table[@id='" + id_format.format(home_team["id"]) + "']")
c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:824: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to ".//table[@id='stats_33c895d4_misc']"
  html_table = tree.find("//table[@id='" + id_format.format(away_team["id"]) + "']")

MultiIndex([('jersey_number',      ''),
            (       'nation',      ''),
            (          'pos',      ''),
            (          'age',      ''),
            (          'min',      ''),
            (  'Performance',  'CrdY'),
            (  'Performance',  'CrdR'),
            (  'Performance', '2CrdY'),
            (  'Performance',   'Fls'),
            (  'Performance',   'Fld'),
            (  'Performance',   'Off'),
            (  'Performance',   'Crs'),
            (  'Performance',   'Int'),
            (  'Performance',  'TklW'),
            (  'Performance', 'PKwon'),
            (  'Performance', 'PKcon'),
            (  'Performance',    'OG'),
            (  'Performance', 'Recov'),
            ( 'Aerial Duels',   'Won'),
            ( 'Aerial Duels',  'Lost'),
            ( 'Aerial Duels',  'Won%'),
            (      'game_id',      '')],
           )

In [42]:
fbref = sd.FBref(leagues="INT-European Championships", seasons='2020-2021', no_cache=False)
player_match_stats = fbref.read_player_season_stats(stat_type="standard")
player_match_stats

[06/07/24 10:57:30] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=407981;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=921241;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py:493: UserWarning: Season id "2021" is ambiguous: interpreting as "20-21"
  warnings.warn(msg, stacklevel=1)

                                                                  nation  \

league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović    Austria
                                          Alessandro Schöpf      Austria
                                          Andreas Ulmer          Austria
                                          Christoph Baumgartner  Austria
                                          Christopher Trimmel    Austria
...                                                                  ...
                                  Wales   Joe Morrell              Wales
                                          Joe Rodon                Wales
                                          Kieffer Moore            Wales
                                          Neco Williams            Wales
                                          Tyler Roberts            Wales

                                                                   pos age  \

league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović       DF  29
                                          Alessandro Schöpf         FW  26
                                          Andreas Ulmer             FW  35
                                          Christoph Baumgartner     FW  21
                                          Christopher Trimmel       DF  33
...                                                                ...  ..
                                  Wales   Joe Morrell               MF  24
                                          Joe Rodon                 DF  23
                                          Kieffer Moore             FW  28
                                          Neco Williams          DF,MF  19
                                          Tyler Roberts             FW  22

                                                                 born  \

league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović    1991
                                          Alessandro Schöpf      1994
                                          Andreas Ulmer          1985
                                          Christoph Baumgartner  1999
                                          Christopher Trimmel    1987
...                                                               ...
                                  Wales   Joe Morrell            1997
                                          Joe Rodon              1997
                                          Kieffer Moore          1992
                                          Neco Williams          2001
                                          Tyler Roberts          1999

                                                                Playing Time  \
                                                                          MP
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović              4
                                          Alessandro Schöpf                2
                                          Andreas Ulmer                    2
                                          Christoph Baumgartner            4
                                          Christopher Trimmel              1
...                                                                      ...
                                  Wales   Joe Morrell                      4
                                          Joe Rodon                        4
                                          Kieffer Moore                    4
                                          Neco Williams                    3
                                          Tyler Roberts                    1

                                                                             \
                                                                Starts  Min
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović        4  338
                                          Alessandro Schöpf          0   90
                                          Andreas Ulmer              2  180
                                          Christoph Baumgartner      4  246
                                          Christopher Trimmel        0    7
...                                                                ...  ...
                                  Wales   Joe Morrell                4  298
                                          Joe Rodon                  4  360
                                          Kieffer Moore              3  288
                                          Neco Williams              1  137
                                          Tyler Roberts              0   13

                                                                      \
                                                                 90s
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović    3.8
                                          Alessandro Schöpf      1.0
                                          Andreas Ulmer          2.0
                                          Christoph Baumgartner  2.7
                                          Christopher Trimmel    0.1
...                                                              ...
                                  Wales   Joe Morrell            3.3
                                          Joe Rodon              4.0
                                          Kieffer Moore          3.2
                                          Neco Williams          1.5
                                          Tyler Roberts          0.1

                                                                Performance  \
                                                                        Gls
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović             0
                                          Alessandro Schöpf               0
                                          Andreas Ulmer                   0
                                          Christoph Baumgartner           1
                                          Christopher Trimmel             0
...                                                                     ...
                                  Wales   Joe Morrell                     0
                                          Joe Rodon                       0
                                          Kieffer Moore                   1
                                          Neco Williams                   0
                                          Tyler Roberts                   0

                                                                     ...  \
                                                                Ast  ...
league                     season team    player                     ...
INT-European Championships 2021   Austria Aleksandar Dragović     0  ...
                                          Alessandro Schöpf       0  ...
                                          Andreas Ulmer           0  ...
                                          Christoph Baumgartner   0  ...
                                          Christopher Trimmel     0  ...
...                                                              ..  ...
                                  Wales   Joe Morrell             1  ...
                                          Joe Rodon               0  ...
                                          Kieffer Moore           0  ...
                                          Neco Williams           0  ...
                                          Tyler Roberts           0  ...

                                                                Per 90 Minutes  \
                                                                           Gls
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović              0.0
                                          Alessandro Schöpf                0.0
                                          Andreas Ulmer                    0.0
                                          Christoph Baumgartner           0.37
                                          Christopher Trimmel              0.0
...                                                                        ...
                                  Wales   Joe Morrell                      0.0
                                          Joe Rodon                        0.0
                                          Kieffer Moore                   0.31
                                          Neco Williams                    0.0
                                          Tyler Roberts                    0.0

                                                                            \
                                                                 Ast   G+A
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović    0.0   0.0
                                          Alessandro Schöpf      0.0   0.0
                                          Andreas Ulmer          0.0   0.0
                                          Christoph Baumgartner  0.0  0.37
                                          Christopher Trimmel    0.0   0.0
...                                                              ...   ...
                                  Wales   Joe Morrell            0.3   0.3
                                          Joe Rodon              0.0   0.0
                                          Kieffer Moore          0.0  0.31
                                          Neco Williams          0.0   0.0
                                          Tyler Roberts          0.0   0.0

                                                                              \
                                                                 G-PK G+A-PK
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović     0.0    0.0
                                          Alessandro Schöpf       0.0    0.0
                                          Andreas Ulmer           0.0    0.0
                                          Christoph Baumgartner  0.37   0.37
                                          Christopher Trimmel     0.0    0.0
...                                                               ...    ...
                                  Wales   Joe Morrell             0.0    0.3
                                          Joe Rodon               0.0    0.0
                                          Kieffer Moore          0.31   0.31
                                          Neco Williams           0.0    0.0
                                          Tyler Roberts           0.0    0.0

                                                                             \
                                                                   xG   xAG
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović    0.03   0.0
                                          Alessandro Schöpf      0.05  0.79
                                          Andreas Ulmer           0.0   0.0
                                          Christoph Baumgartner   0.2  0.02
                                          Christopher Trimmel    <NA>  <NA>
...                                                               ...   ...
                                  Wales   Joe Morrell            0.01  0.04
                                          Joe Rodon              0.01   0.1
                                          Kieffer Moore           0.1  0.03
                                          Neco Williams           0.0  0.06
                                          Tyler Roberts           0.0   0.0

                                                                              \
                                                                xG+xAG  npxG
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović     0.03  0.03
                                          Alessandro Schöpf       0.84  0.05
                                          Andreas Ulmer            0.0   0.0
                                          Christoph Baumgartner   0.21   0.2
                                          Christopher Trimmel     <NA>  <NA>
...                                                                ...   ...
                                  Wales   Joe Morrell             0.05  0.01
                                          Joe Rodon                0.1  0.01
                                          Kieffer Moore           0.13   0.1
                                          Neco Williams           0.06   0.0
                                          Tyler Roberts            0.0   0.0


                                                                npxG+xAG
league                     season team    player
INT-European Championships 2021   Austria Aleksandar Dragović       0.03
                                          Alessandro Schöpf         0.84
                                          Andreas Ulmer              0.0
                                          Christoph Baumgartner     0.21
                                          Christopher Trimmel       <NA>
...                                                                  ...
                                  Wales   Joe Morrell               0.05
                                          Joe Rodon                  0.1
                                          Kieffer Moore             0.13
                                          Neco Williams             0.06
                                          Tyler Roberts              0.0

[490 rows x 33 columns]

In [1]:
import soccerdata as sd
import datetime
import pandas as pd
import hashlib

[06/18/24 12:10:17] INFO     No custom team name replacements found. You can configure these in       ]8;id=566810;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=345304;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_config.py#87\87]8;;\
                             C:\Users\jdelavande\soccerdata\config\teamname_replacements.json.

                    INFO     Custom league dict loaded from                                          ]8;id=443812;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=841239;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_config.py#180\180]8;;\
                             C:\Users\jdelavande\soccerdata\config\league_dict.json.

In [2]:
current_season = datetime.datetime.now().year
get_current_season_only = True
use_cache = True

In [11]:
leagues = ["INT-World Cup"]
seasons = [f"{str(year)}-{str(year+1)[2:]}" for year in range(1930, current_season+1, 4)]
[seasons.remove(f"{str(year)}-{str(year+1)[2:]}") for year in range(1942, 1948, 4)]
if get_current_season_only:
    current_season_int = f"{current_season}-{str(current_season+1)[2:]}"
    seasons = [current_season_int] if current_season_int in seasons else []
fbref = sd.FBref(leagues=leagues, seasons=seasons)
matches_wc = fbref.read_schedule(force_cache=use_cache) if seasons else None
matches_wc = matches_wc.reset_index() if matches_wc is not None else None
print(f"seasons: {seasons}")
matches_wc

[06/18/24 12:12:24] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=111712;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=364665;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

seasons: []

In [8]:
leagues = ['INT-European Championships']
seasons = list(range(2000, current_season+1, 4))
if get_current_season_only:
    seasons = [current_season] if current_season in seasons else []
fbref = sd.FBref(leagues=leagues, seasons=seasons)
euro_schedule = fbref.read_schedule(force_cache=use_cache) if seasons else None
euro_schedule = euro_schedule.reset_index() if euro_schedule is not None else None
print(f"seasons: {seasons}")

euro_schedule.head()

[06/18/24 12:11:30] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=235486;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=558193;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>
seasons: [2024]

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py:493: UserWarning: Season id "2021" is ambiguous: interpreting as "20-21"
  warnings.warn(msg, stacklevel=1)

,league,season,game,round,week,day,date,time,home_team,home_xg,score,away_xg,away_team,attendance,venue,referee,match_report,notes,game_id
0,INT-European Championships,2425,2024-06-14 Germany-Scotland,Group stage,1,Fri,2024-06-14,21:00,Germany,2.1,5–1,0.0,Scotland,65052,Allianz Arena,Clément Turpin,/en/matches/bd775264/Germany-Scotland-June-14-...,<NA>,bd775264
1,INT-European Championships,2425,2024-06-15 Hungary-Switzerland,Group stage,1,Sat,2024-06-15,15:00,Hungary,1.3,1–3,2.3,Switzerland,41676,RheinEnergieSTADION,Slavko Vinčič,/en/matches/c15ec4e7/Hungary-Switzerland-June-...,<NA>,c15ec4e7
2,INT-European Championships,2425,2024-06-15 Italy-Albania,Group stage,1,Sat,2024-06-15,21:00,Italy,1.5,2–1,0.5,Albania,60512,Signal Iduna Park,Felix Zwayer,/en/matches/4891e62c/Italy-Albania-June-15-202...,<NA>,4891e62c
3,INT-European Championships,2425,2024-06-15 Spain-Croatia,Group stage,1,Sat,2024-06-15,18:00,Spain,2.0,3–0,2.1,Croatia,68844,Olympiastadion Berlin,Michael Oliver,/en/matches/b996c4de/Spain-Croatia-June-15-202...,<NA>,b996c4de
4,INT-European Championships,2425,2024-06-16 Poland-Netherlands,Group stage,1,Sun,2024-06-16,15:00,Poland,1.3,1–2,1.5,Netherlands,48117,Volksparkstadion,Artur Soares Dias,/en/matches/923de563/Poland-Netherlands-June-1...,<NA>,923de563

In [10]:
leagues = ["Big 5 European Leagues Combined"]
seasons = [f"{str(year)[2:]}-{str(year+1)[2:]}" for year in range(1930, current_season+1)]
[seasons.remove(f"{str(year)[2:]}-{str(year+1)[2:]}") for year in range(1939, 1946)]
if get_current_season_only:
    current_season_big5 = f"{str(current_season-1)[2:]}-{str(current_season)[2:]}"
    seasons = [current_season_big5] if current_season_big5 in seasons else []
fbref = sd.FBref(leagues=leagues, seasons=seasons)
big5 = fbref.read_schedule(force_cache=use_cache) if seasons else None
big5 = big5.reset_index() if big5 is not None else None
print(f"seasons: {seasons}")
big5.head()

[06/18/24 12:11:57] INFO     Saving cached data to C:\Users\jdelavande\soccerdata\data\FBref          ]8;id=241084;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=588028;file://c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\_common.py#92\92]8;;\

<_io.BufferedReader name='C:\\Users\\jdelavande\\soccerdata\\data\\FBref\\leagues.html'>
seasons: ['23-24']

c:\Users\jdelavande\Projects\optim-sportbet\venv\lib\site-packages\soccerdata\fbref.py:686: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(schedule)

,league,season,game,week,day,date,time,home_team,home_xg,score,away_xg,away_team,attendance,venue,referee,match_report,notes,round,game_id
0,ENG-Premier League,2324,2023-08-11 Burnley-Manchester City,1,Fri,2023-08-11,20:00,Burnley,0.3,0–3,1.9,Manchester City,21572,Turf Moor,Craig Pawson,/en/matches/3a6836b4/Burnley-Manchester-City-A...,<NA>,<NA>,3a6836b4
1,ENG-Premier League,2324,2023-08-12 Arsenal-Nott'ham Forest,1,Sat,2023-08-12,12:30,Arsenal,0.8,2–1,1.2,Nott'ham Forest,59984,Emirates Stadium,Michael Oliver,/en/matches/26a7f90c/Arsenal-Nottingham-Forest...,<NA>,<NA>,26a7f90c
2,ENG-Premier League,2324,2023-08-12 Bournemouth-West Ham,1,Sat,2023-08-12,15:00,Bournemouth,1.3,1–1,1.1,West Ham,11245,Vitality Stadium,Peter Bankes,/en/matches/d6bbf293/Bournemouth-West-Ham-Unit...,<NA>,<NA>,d6bbf293
3,ENG-Premier League,2324,2023-08-12 Brighton-Luton Town,1,Sat,2023-08-12,15:00,Brighton,4.0,4–1,1.5,Luton Town,31872,The American Express Community Stadium,David Coote,/en/matches/56a137f7/Brighton-and-Hove-Albion-...,<NA>,<NA>,56a137f7
4,ENG-Premier League,2324,2023-08-12 Everton-Fulham,1,Sat,2023-08-12,15:00,Everton,2.7,0–1,1.5,Fulham,39940,Goodison Park,Stuart Attwell,/en/matches/15addfc7/Everton-Fulham-August-12-...,<NA>,<NA>,15addfc7

In [30]:
matches_wc = matches_wc.reset_index(drop=True) if matches_wc is not None else None
euro_schedule = euro_schedule.reset_index(drop=True) if euro_schedule is not None else None
big5 = big5.reset_index(drop=True) if big5 is not None else None
fbref_df = pd.concat([matches_wc, euro_schedule, big5], ignore_index=True)

C:\Users\jdelavande\AppData\Local\Temp\ipykernel_19536\1391937379.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  fbref_df = pd.concat([matches_wc, euro_schedule, big5], ignore_index=True)

In [34]:
big5

,week,day,date,time,home_team,home_xg,score,away_xg,away_team,attendance,venue,referee,match_report,notes,round,game_id
0,1,Fri,2023-08-11,20:00,Burnley,0.3,0–3,1.9,Manchester City,21572,Turf Moor,Craig Pawson,/en/matches/3a6836b4/Burnley-Manchester-City-A...,<NA>,<NA>,3a6836b4
1,1,Sat,2023-08-12,12:30,Arsenal,0.8,2–1,1.2,Nott'ham Forest,59984,Emirates Stadium,Michael Oliver,/en/matches/26a7f90c/Arsenal-Nottingham-Forest...,<NA>,<NA>,26a7f90c
2,1,Sat,2023-08-12,15:00,Bournemouth,1.3,1–1,1.1,West Ham,11245,Vitality Stadium,Peter Bankes,/en/matches/d6bbf293/Bournemouth-West-Ham-Unit...,<NA>,<NA>,d6bbf293
3,1,Sat,2023-08-12,15:00,Brighton,4.0,4–1,1.5,Luton Town,31872,The American Express Community Stadium,David Coote,/en/matches/56a137f7/Brighton-and-Hove-Albion-...,<NA>,<NA>,56a137f7
4,1,Sat,2023-08-12,15:00,Everton,2.7,0–1,1.5,Fulham,39940,Goodison Park,Stuart Attwell,/en/matches/15addfc7/Everton-Fulham-August-12-...,<NA>,<NA>,15addfc7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1751,38,Sun,2024-05-26,20:45,Frosinone,0.8,0–1,0.7,Udinese,16190,Stadio Benito Stirpe,Daniele Doveri,/en/matches/65f327b4/Frosinone-Udinese-May-26-...,<NA>,<NA>,65f327b4
1752,38,Sun,2024-05-26,20:45,Hellas Verona,1.7,2–2,2.4,Inter,22447,Stadio Marc'Antonio Bentegodi,Luca Zufferli,/en/matches/d97ac2fa/Hellas-Verona-Internazion...,<NA>,<NA>,d97ac2fa
1753,38,Sun,2024-05-26,20:45,Lazio,1.0,1–1,1.1,Sassuolo,56000,Stadio Olimpico,Paride Tremolada,/en/matches/2b4865cf/Lazio-Sassuolo-May-26-202...,<NA>,<NA>,2b4865cf
1754,38,Sun,2024-05-26,18:00,Napoli,1.5,0–0,0.5,Lecce,41000,Stadio Diego Armando Maradona,Federico Dionisi,/en/matches/c234b266/Napoli-Lecce-May-26-2024-...,<NA>,<NA>,c234b266
1755,29,Sun,2024-06-02,18:00,Atalanta,1.7,2–3,1.2,Fiorentina,14851,Gewiss Stadium,Daniele Orsato,/en/matches/ceb127e3/Atalanta-Fiorentina-June-...,<NA>,<NA>,ceb127e3

In [31]:
fbref_df

,round,week,day,date,time,home_team,home_xg,score,away_xg,away_team,attendance,venue,referee,match_report,notes,game_id
0,Group stage,1,Fri,2024-06-14,21:00,Germany,2.1,5–1,0.0,Scotland,65052,Allianz Arena,Clément Turpin,/en/matches/bd775264/Germany-Scotland-June-14-...,<NA>,bd775264
1,Group stage,1,Sat,2024-06-15,15:00,Hungary,1.3,1–3,2.3,Switzerland,41676,RheinEnergieSTADION,Slavko Vinčič,/en/matches/c15ec4e7/Hungary-Switzerland-June-...,<NA>,c15ec4e7
2,Group stage,1,Sat,2024-06-15,21:00,Italy,1.5,2–1,0.5,Albania,60512,Signal Iduna Park,Felix Zwayer,/en/matches/4891e62c/Italy-Albania-June-15-202...,<NA>,4891e62c
3,Group stage,1,Sat,2024-06-15,18:00,Spain,2.0,3–0,2.1,Croatia,68844,Olympiastadion Berlin,Michael Oliver,/en/matches/b996c4de/Spain-Croatia-June-15-202...,<NA>,b996c4de
4,Group stage,1,Sun,2024-06-16,15:00,Poland,1.3,1–2,1.5,Netherlands,48117,Volksparkstadion,Artur Soares Dias,/en/matches/923de563/Poland-Netherlands-June-1...,<NA>,923de563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1787,<NA>,38,Sun,2024-05-26,20:45,Frosinone,0.8,0–1,0.7,Udinese,16190,Stadio Benito Stirpe,Daniele Doveri,/en/matches/65f327b4/Frosinone-Udinese-May-26-...,<NA>,65f327b4
1788,<NA>,38,Sun,2024-05-26,20:45,Hellas Verona,1.7,2–2,2.4,Inter,22447,Stadio Marc'Antonio Bentegodi,Luca Zufferli,/en/matches/d97ac2fa/Hellas-Verona-Internazion...,<NA>,d97ac2fa
1789,<NA>,38,Sun,2024-05-26,20:45,Lazio,1.0,1–1,1.1,Sassuolo,56000,Stadio Olimpico,Paride Tremolada,/en/matches/2b4865cf/Lazio-Sassuolo-May-26-202...,<NA>,2b4865cf
1790,<NA>,38,Sun,2024-05-26,18:00,Napoli,1.5,0–0,0.5,Lecce,41000,Stadio Diego Armando Maradona,Federico Dionisi,/en/matches/c234b266/Napoli-Lecce-May-26-2024-...,<NA>,c234b266
1791,<NA>,29,Sun,2024-06-02,18:00,Atalanta,1.7,2–3,1.2,Fiorentina,14851,Gewiss Stadium,Daniele Orsato,/en/matches/ceb127e3/Atalanta-Fiorentina-June-...,<NA>,ceb127e3

In [29]:
fbref_df             = fbref_df.reset_index()
fbref_df['date']     = pd.to_datetime(fbref_df['date'])
fbref_df['time']     = pd.to_datetime(fbref_df['time']).dt.time
fbref_df['index']    = fbref_df['game'].apply(lambda x: int(hashlib.sha256(x.encode()).hexdigest()[:6], 16))
fbref_df['home_g']   = fbref_df['score'].apply(lambda x: x.split('–')[0][-1] if not pd.isna(x) else x)
fbref_df['away_g']   = fbref_df['score'].apply(lambda x: x.split('–')[1][0] if not pd.isna(x) else x)
fbref_df['home_sat'] = fbref_df['score'].apply(lambda x: x.split('–')[0].split('(')[1][0] if not pd.isna(x) and '(' in x else pd.NA)
fbref_df['away_sat'] = fbref_df['score'].apply(lambda x: x.split('–')[1].split('(')[1][0] if not pd.isna(x) and '(' in x else pd.NA)
fbref_df['home_g']   = pd.to_numeric(fbref_df['home_g'], errors='coerce')
fbref_df['away_g']   = pd.to_numeric(fbref_df['away_g'], errors='coerce')
fbref_df['home_sat'] = pd.to_numeric(fbref_df['home_sat'], errors='coerce')
fbref_df['away_sat'] = pd.to_numeric(fbref_df['away_sat'], errors='coerce')

C:\Users\jdelavande\AppData\Local\Temp\ipykernel_19536\1545645433.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  fbref_df['time']     = pd.to_datetime(fbref_df['time']).dt.time

KeyError: 'game'

In [12]:
matches_wc