In [1]:
import optibet_lib.soccerdata as sd

[09/17/25 12:29:33] INFO     No custom team name replacements found. You can configure these in       ]8;id=857582;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_config.py\_config.py]8;;\:]8;id=701757;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_config.py#87\87]8;;\
                             lib/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=552012;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_config.py\_config.py]8;;\:]8;id=1322;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_config.py#182\182]8;;\
                             lib/soccerdata/config/league_dict.json.

In [ ]:
sofifa_all = sd.SoFIFA(versions="latest", no_cache=True)
teams_name = ["SK Slavia Praha", "FK Bodø/Glimt", "Ajax"]
team_ratings_all = sofifa_all.read_team_ratings_by_name(teams_name)

[09/17/25 12:29:41] INFO     Saving cached data to lib/soccerdata/data/SoFIFA                         ]8;id=326894;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_common.py\_common.py]8;;\:]8;id=969139;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_common.py#92\92]8;;\

[09/17/25 12:30:07] INFO     Searching for team 'SK Slavia Praha' in version Jul 17, 2025...          ]8;id=931018;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=201972;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py#518\518]8;;\

In [5]:
team_ratings_all

,overall,attack,midfield,defence,transfer_budget,club_worth,build_up_speed,build_up_dribbling,build_up_passing,build_up_positioning,...,defence_pressure,defence_team_width,defence_defender_line,defence_domestic_prestige,international_prestige,players,starting_xi_average_age,whole_team_average_age,fifa_edition,update
team,,,,,,,,,,,,,,,,,,,,,
SK Slavia Praha,74,73,75,74,€0,€65M,Slow,Little,Short,Organised,...,Deep,Narrow,Cover,10,4,27,26.64,23.89,FC 25,"Jul 17, 2025"

In [6]:
sofifa_all = sd.SoFIFA(versions="latest", no_cache=False)
team_ratings_all = sofifa_all.read_team_ratings()
team_ratings_all

[09/17/25 12:27:26] INFO     Saving cached data to lib/soccerdata/data/SoFIFA                         ]8;id=363071;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_common.py\_common.py]8;;\:]8;id=732769;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/_common.py#92\92]8;;\

                    INFO     [1/5] Retrieving teams for ENG-Premier League in Jul 17, 2025 edition    ]8;id=252417;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=370219;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py#346\346]8;;\

[09/17/25 12:27:27] INFO     [2/5] Retrieving teams for ESP-La Liga in Jul 17, 2025 edition           ]8;id=851044;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=505962;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py#346\346]8;;\

[09/17/25 12:27:28] INFO     [3/5] Retrieving teams for ITA-Serie A in Jul 17, 2025 edition           ]8;id=474928;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=324844;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py#346\346]8;;\

[09/17/25 12:27:30] INFO     [4/5] Retrieving teams for GER-Bundesliga in Jul 17, 2025 edition        ]8;id=269191;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=197546;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py#346\346]8;;\

[09/17/25 12:27:31] INFO     [5/5] Retrieving teams for FRA-Ligue 1 in Jul 17, 2025 edition           ]8;id=72118;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py\sofifa.py]8;;\:]8;id=529020;file:///Users/huggingfaceit/code/SoccerBetMLOptimizer/optibet_lib/src/optibet_lib/soccerdata/sofifa.py#346\346]8;;\

                                          overall attack midfield defence  \
league             team
ENG-Premier League AFC Bournemouth             77     80       77      77
                   Arsenal                     83     83       85      81
                   Aston Villa                 81     84       80      80
                   Brentford                   77     80       76      76
                   Brighton & Hove Albion      78     78       77      77
...                                           ...    ...      ...     ...
ITA-Serie A        Parma                       73     69       74      69
                   Roma                        79     78       79      79
                   Torino                      76     76       76      75
                   Udinese                     73     75       73      73
                   Venezia                     71     71       72      69

                                          transfer_budget club_worth  \
league             team
ENG-Premier League AFC Bournemouth                     €0      €410M
                   Arsenal                             €0      €1.9B
                   Aston Villa                         €0      €800M
                   Brentford                           €0      €430M
                   Brighton & Hove Albion              €0      €675M
...                                                   ...        ...
ITA-Serie A        Parma                               €0       €75M
                   Roma                                €0      €660M
                   Torino                              €0      €180M
                   Udinese                             €0      €130M
                   Venezia                             €0       €40M

                                          build_up_speed build_up_dribbling  \
league             team
ENG-Premier League AFC Bournemouth                  Slow             Little
                   Arsenal                          Slow             Little
                   Aston Villa                      Slow             Little
                   Brentford                        Slow             Little
                   Brighton & Hove Albion           Slow             Little
...                                                  ...                ...
ITA-Serie A        Parma                            Slow             Little
                   Roma                             Slow             Little
                   Torino                           Slow             Little
                   Udinese                          Slow             Little
                   Venezia                          Slow             Little

                                          build_up_passing  \
league             team
ENG-Premier League AFC Bournemouth                   Short
                   Arsenal                           Short
                   Aston Villa                       Short
                   Brentford                         Short
                   Brighton & Hove Albion            Short
...                                                    ...
ITA-Serie A        Parma                             Short
                   Roma                              Short
                   Torino                            Short
                   Udinese                           Short
                   Venezia                           Short

                                          build_up_positioning  ...  \
league             team                                         ...
ENG-Premier League AFC Bournemouth                   Organised  ...
                   Arsenal                           Organised  ...
                   Aston Villa                       Organised  ...
                   Brentford                         Organised  ...
                   Brighton & Hove Albion            Organised  ...
...                                                        ...  ...
ITA-Serie A        Parma                             Organised  ...
                   Roma                              Organised  ...
                   Torino                            Organised  ...
                   Udinese                           Organised  ...
                   Venezia                           Organised  ...

                                          defence_pressure defence_team_width  \
league             team
ENG-Premier League AFC Bournemouth                    Deep             Narrow
                   Arsenal                            Deep             Narrow
                   Aston Villa                        Deep             Narrow
                   Brentford                          Deep             Narrow
                   Brighton & Hove Albion             Deep             Narrow
...                                                    ...                ...
ITA-Serie A        Parma                              Deep             Narrow
                   Roma                               Deep             Narrow
                   Torino                             Deep             Narrow
                   Udinese                            Deep             Narrow
                   Venezia                            Deep             Narrow

                                          defence_defender_line  \
league             team
ENG-Premier League AFC Bournemouth                        Cover
                   Arsenal                                Cover
                   Aston Villa                            Cover
                   Brentford                              Cover
                   Brighton & Hove Albion                 Cover
...                                                         ...
ITA-Serie A        Parma                                  Cover
                   Roma                                   Cover
                   Torino                                 Cover
                   Udinese                                Cover
                   Venezia                                Cover

                                          defence_domestic_prestige  \
league             team
ENG-Premier League AFC Bournemouth                                2
                   Arsenal                                        9
                   Aston Villa                                    7
                   Brentford                                      3
                   Brighton & Hove Albion                         5
...                                                             ...
ITA-Serie A        Parma                                          5
                   Roma                                           8
                   Torino                                         6
                   Udinese                                        3
                   Venezia                                        1

                                          international_prestige players  \
league             team
ENG-Premier League AFC Bournemouth                             2      30
                   Arsenal                                     9      25
                   Aston Villa                                 6      24
                   Brentford                                   2      26
                   Brighton & Hove Albion                      5      30
...                                                          ...     ...
ITA-Serie A        Parma                                       3      31
                   Roma                                        7      25
                   Torino                                      4      32
                   Udinese                                     3      28
                   Venezia                                     1      30

                                          starting_xi_average_age  \
league             team
ENG-Premier League AFC Bournemouth                          24.45
                   Arsenal                                  24.55
                   Aston Villa                              26.82
                   Brentford                                24.64
                   Brighton & Hove Albion                   24.09
...                                                           ...
ITA-Serie A        Parma                                    22.18
                   Roma                                     26.27
                   Torino                                   25.91
                   Udinese                                  26.36
                   Venezia                                  23.91

                                          whole_team_average_age fifa_edition  \
league             team
ENG-Premier League AFC Bournemouth                         22.83        FC 25
                   Arsenal                                 25.44        FC 25
                   Aston Villa                             26.29        FC 25
                   Brentford                               24.08        FC 25
                   Brighton & Hove Albion                  24.43        FC 25
...                                                          ...          ...
ITA-Serie A        Parma                                   23.52        FC 25
                   Roma                                    24.68        FC 25
                   Torino                                  24.75        FC 25
                   Udinese                                 25.25        FC 25
                   Venezia                                 25.00        FC 25

                                                 update
league             team
ENG-Premier League AFC Bournemouth         Jul 17, 2025
                   Arsenal                 Jul 17, 2025
                   Aston Villa             Jul 17, 2025
                   Brentford               Jul 17, 2025
                   Brighton & Hove Albion  Jul 17, 2025
...                                                 ...
ITA-Serie A        Parma                   Jul 17, 2025
                   Roma                    Jul 17, 2025
                   Torino                  Jul 17, 2025
                   Udinese                 Jul 17, 2025
                   Venezia                 Jul 17, 2025

[96 rows x 25 columns]